from .core import AIModel, Quantization

MODELS = [
    AIModel(
        id="deepseek-r1-1.5b",
        name="DeepSeek R1 1.5B",
        provider="DeepSeek",
        family="DeepSeek",
        params="1.5B",
        params_billions=1.5,
        architecture="dense",
        context_length=65536,
        use_case=['reasoning'],
        description="Tiny reasoning model distilled from R1",
        min_ram_gb=1.0,
        recommended_ram_gb=2.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=1.0, disk_gb=0.5, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=1.2, disk_gb=0.6, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=1.3, disk_gb=0.7, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=1.5, disk_gb=0.9, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=1.7, disk_gb=1.1, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=2.0, disk_gb=1.5, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=3.6, disk_gb=2.9, quality="lossless"),
        ],
        ollama_id="deepseek-r1:1.5b",
        license="MIT",
    ),
    AIModel(
        id="deepseek-r1-7b",
        name="DeepSeek R1 Distill 7B",
        provider="DeepSeek",
        family="DeepSeek",
        params="7B",
        params_billions=7,
        architecture="dense",
        context_length=65536,
        use_case=['reasoning'],
        description="R1 reasoning distilled into Qwen 7B",
        min_ram_gb=3.9,
        recommended_ram_gb=6.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=2.7, disk_gb=2.1, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=3.6, disk_gb=3.0, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=4.1, disk_gb=3.4, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=5.0, disk_gb=4.3, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=5.9, disk_gb=5.1, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=7.7, disk_gb=6.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=14.8, disk_gb=13.7, quality="lossless"),
        ],
        ollama_id="deepseek-r1:7b",
        license="MIT",
    ),
    AIModel(
        id="deepseek-r1-14b",
        name="DeepSeek R1 Distill 14B",
        provider="DeepSeek",
        family="DeepSeek",
        params="14B",
        params_billions=14,
        architecture="dense",
        context_length=65536,
        use_case=['reasoning'],
        description="R1 reasoning distilled into Qwen 14B",
        min_ram_gb=7.8,
        recommended_ram_gb=13.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=5.0, disk_gb=4.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=6.8, disk_gb=6.0, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=7.7, disk_gb=6.8, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=9.5, disk_gb=8.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=11.3, disk_gb=10.3, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=14.8, disk_gb=13.7, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=29.2, disk_gb=27.4, quality="lossless"),
        ],
        ollama_id="deepseek-r1:14b",
        license="MIT",
    ),
    AIModel(
        id="deepseek-r1-32b",
        name="DeepSeek R1 Distill 32B",
        provider="DeepSeek",
        family="DeepSeek",
        params="32B",
        params_billions=32,
        architecture="dense",
        context_length=65536,
        use_case=['reasoning'],
        description="R1 reasoning distilled into Qwen 32B — sweet spot",
        min_ram_gb=17.9,
        recommended_ram_gb=29.8,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=10.7, disk_gb=9.8, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=14.8, disk_gb=13.7, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=16.9, disk_gb=15.6, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=21.0, disk_gb=19.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=25.1, disk_gb=23.5, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=33.3, disk_gb=31.3, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=66.1, disk_gb=62.6, quality="lossless"),
        ],
        ollama_id="deepseek-r1:32b",
        featured=True,
        license="MIT",
    ),
    AIModel(
        id="deepseek-r1",
        name="DeepSeek R1",
        provider="DeepSeek",
        family="DeepSeek",
        params="671B",
        params_billions=671,
        architecture="moe",
        context_length=65536,
        use_case=['reasoning'],
        description="Massive MoE reasoning model — 37B active",
        min_ram_gb=375.0,
        recommended_ram_gb=624.9,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=215.3, disk_gb=205.1, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=301.2, disk_gb=287.1, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=344.2, disk_gb=328.1, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=430.1, disk_gb=410.1, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=516.1, disk_gb=492.1, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=687.9, disk_gb=656.2, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=1375.3, disk_gb=1312.3, quality="lossless"),
        ],
        active_params="37B active",
        moe_info={'numExperts': 256, 'activeExperts': 8, 'activeParameters': 37000000000},
        ollama_id="deepseek-r1:671b",
        featured=True,
        license="MIT",
    ),
    AIModel(
        id="deepseek-v3.1",
        name="DeepSeek V3.1",
        provider="DeepSeek",
        family="DeepSeek",
        params="671B",
        params_billions=671,
        architecture="moe",
        context_length=131072,
        use_case=['chat', 'code', 'reasoning'],
        description="Improved V3 with hybrid thinking and tool use",
        min_ram_gb=375.0,
        recommended_ram_gb=624.9,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=215.3, disk_gb=205.1, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=301.2, disk_gb=287.1, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=344.2, disk_gb=328.1, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=430.1, disk_gb=410.1, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=516.1, disk_gb=492.1, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=687.9, disk_gb=656.2, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=1375.3, disk_gb=1312.3, quality="lossless"),
        ],
        active_params="37B active",
        moe_info={'numExperts': 256, 'activeExperts': 8, 'activeParameters': 37000000000},
        ollama_id="deepseek-v3.1",
        license="MIT",
    ),
    AIModel(
        id="deepseek-v3.2",
        name="DeepSeek V3.2",
        provider="DeepSeek",
        family="DeepSeek",
        params="685B",
        params_billions=685,
        architecture="moe",
        context_length=131072,
        use_case=['chat', 'code', 'reasoning'],
        description="State-of-the-art MoE — 37B active params",
        min_ram_gb=382.8,
        recommended_ram_gb=638.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=219.8, disk_gb=209.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=307.5, disk_gb=293.1, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=351.4, disk_gb=334.9, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=439.1, disk_gb=418.7, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=526.8, disk_gb=502.4, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=702.3, disk_gb=669.9, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=1404.0, disk_gb=1339.7, quality="lossless"),
        ],
        active_params="37B active",
        moe_info={'numExperts': 256, 'activeExperts': 8, 'activeParameters': 37000000000},
        ollama_id="deepseek-v3.2",
        featured=True,
        license="MIT",
    ),
]
