from .core import AIModel, Quantization

MODELS = [
    AIModel(
        id="gemma3-1b",
        name="Gemma 3 1B",
        provider="Google",
        family="Gemma",
        params="1B",
        params_billions=1,
        architecture="dense",
        context_length=32768,
        use_case=['chat', 'edge'],
        description="Google's tiny Gemma for on-device",
        min_ram_gb=1.0,
        recommended_ram_gb=2.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=0.8, disk_gb=0.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=0.9, disk_gb=0.4, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=1.0, disk_gb=0.5, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=1.1, disk_gb=0.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=1.3, disk_gb=0.7, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=1.5, disk_gb=1.0, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=2.5, disk_gb=2.0, quality="lossless"),
        ],
        ollama_id="gemma3:1b",
        license="Gemma",
    ),
    AIModel(
        id="gemma2-2b",
        name="Gemma 2 2B",
        provider="Google",
        family="Gemma",
        params="2B",
        params_billions=2,
        architecture="dense",
        context_length=8192,
        use_case=['chat', 'edge'],
        description="Google's compact open model",
        min_ram_gb=1.1,
        recommended_ram_gb=2.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=1.1, disk_gb=0.6, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=1.4, disk_gb=0.9, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=1.5, disk_gb=1.0, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=1.8, disk_gb=1.2, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=2.0, disk_gb=1.5, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=2.5, disk_gb=2.0, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=4.6, disk_gb=3.9, quality="lossless"),
        ],
        ollama_id="gemma2:2b",
        license="Gemma",
    ),
    AIModel(
        id="gemma3-4b",
        name="Gemma 3 4B",
        provider="Google",
        family="Gemma",
        params="4B",
        params_billions=4,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'vision'],
        description="Multimodal Gemma with 128K context",
        min_ram_gb=2.2,
        recommended_ram_gb=3.7,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=1.8, disk_gb=1.2, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=2.3, disk_gb=1.7, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=2.5, disk_gb=2.0, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=3.1, disk_gb=2.4, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=3.6, disk_gb=2.9, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=4.6, disk_gb=3.9, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=8.7, disk_gb=7.8, quality="lossless"),
        ],
        ollama_id="gemma3:4b",
        license="Gemma",
    ),
    AIModel(
        id="gemma4-e2b-it",
        name="Gemma 4 E2B IT",
        provider="Google",
        family="Gemma",
        params="5B",
        params_billions=5,
        architecture="dense",
        context_length=262144,
        use_case=['chat', 'vision'],
        description="Gemma 4 efficient instruct model (official)",
        min_ram_gb=2.8,
        recommended_ram_gb=4.7,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=2.1, disk_gb=1.5, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=2.7, disk_gb=2.1, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=3.1, disk_gb=3.2, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=3.7, disk_gb=3.1, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=4.3, disk_gb=3.6, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=5.6, disk_gb=4.6, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=10.7, disk_gb=9.8, quality="lossless"),
        ],
        license="Gemma",
    ),
    AIModel(
        id="gemma4-e2b",
        name="Gemma 4 E2B",
        provider="Google",
        family="Gemma",
        params="5B",
        params_billions=5,
        architecture="dense",
        context_length=262144,
        use_case=['vision'],
        description="Gemma 4 efficient base model (official)",
        min_ram_gb=2.8,
        recommended_ram_gb=4.7,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=2.1, disk_gb=1.5, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=2.7, disk_gb=2.1, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=3.1, disk_gb=2.4, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=3.7, disk_gb=3.1, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=4.3, disk_gb=3.7, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=5.6, disk_gb=4.9, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=10.7, disk_gb=9.8, quality="lossless"),
        ],
        license="Gemma",
    ),
    AIModel(
        id="gemma4-e4b-it",
        name="Gemma 4 E4B IT",
        provider="Google",
        family="Gemma",
        params="8B",
        params_billions=8,
        architecture="dense",
        context_length=262144,
        use_case=['chat', 'vision'],
        description="Gemma 4 balanced instruct model (official)",
        min_ram_gb=4.5,
        recommended_ram_gb=7.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=3.1, disk_gb=2.4, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=4.1, disk_gb=3.4, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=4.6, disk_gb=5, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=5.6, disk_gb=4.9, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=6.6, disk_gb=5.8, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=8.7, disk_gb=7.5, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=16.9, disk_gb=15.6, quality="lossless"),
        ],
        license="Gemma",
    ),
    AIModel(
        id="gemma4-e4b",
        name="Gemma 4 E4B",
        provider="Google",
        family="Gemma",
        params="8B",
        params_billions=8,
        architecture="dense",
        context_length=262144,
        use_case=['vision'],
        description="Gemma 4 balanced base model (official)",
        min_ram_gb=4.5,
        recommended_ram_gb=7.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=3.1, disk_gb=2.4, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=4.1, disk_gb=3.4, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=4.6, disk_gb=3.9, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=5.6, disk_gb=4.9, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=6.6, disk_gb=5.9, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=8.7, disk_gb=7.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=16.9, disk_gb=15.6, quality="lossless"),
        ],
        license="Gemma",
    ),
]
