from .core import AIModel, Quantization

MODELS = [
    AIModel(
        id="gemma2-9b",
        name="Gemma 2 9B",
        provider="Google",
        family="Gemma",
        params="9B",
        params_billions=9,
        architecture="dense",
        context_length=8192,
        use_case=['chat', 'reasoning'],
        description="Google's best mid-size open model",
        min_ram_gb=5.0,
        recommended_ram_gb=8.4,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=3.4, disk_gb=2.8, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=4.5, disk_gb=3.9, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=5.1, disk_gb=4.4, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=6.3, disk_gb=5.5, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=7.4, disk_gb=6.6, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=9.7, disk_gb=8.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=18.9, disk_gb=17.6, quality="lossless"),
        ],
        ollama_id="gemma2:9b",
        license="Gemma",
    ),
    AIModel(
        id="gemma3-12b",
        name="Gemma 3 12B",
        provider="Google",
        family="Gemma",
        params="12B",
        params_billions=12,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'vision', 'reasoning'],
        description="Multimodal Gemma with 128K context",
        min_ram_gb=6.7,
        recommended_ram_gb=11.2,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=4.3, disk_gb=3.7, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=5.9, disk_gb=5.1, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=6.6, disk_gb=5.9, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=8.2, disk_gb=7.3, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=9.7, disk_gb=8.8, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=12.8, disk_gb=11.7, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=25.1, disk_gb=23.5, quality="lossless"),
        ],
        ollama_id="gemma3:12b",
        license="Gemma",
    ),
    AIModel(
        id="gemma2-27b",
        name="Gemma 2 27B",
        provider="Google",
        family="Gemma",
        params="27B",
        params_billions=27,
        architecture="dense",
        context_length=8192,
        use_case=['chat', 'reasoning'],
        description="Google's largest Gemma 2 model",
        min_ram_gb=15.1,
        recommended_ram_gb=25.1,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=9.1, disk_gb=8.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=12.6, disk_gb=11.6, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=14.3, disk_gb=13.2, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=17.8, disk_gb=16.5, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=21.2, disk_gb=19.8, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=28.2, disk_gb=26.4, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=55.8, disk_gb=52.8, quality="lossless"),
        ],
        ollama_id="gemma2:27b",
        license="Gemma",
    ),
    AIModel(
        id="gemma3-27b",
        name="Gemma 3 27B",
        provider="Google",
        family="Gemma",
        params="27B",
        params_billions=27,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'vision', 'reasoning'],
        description="Google's flagship Gemma 3 model",
        min_ram_gb=15.1,
        recommended_ram_gb=25.1,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=9.1, disk_gb=8.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=12.6, disk_gb=11.6, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=14.3, disk_gb=13.2, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=17.8, disk_gb=16.5, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=21.2, disk_gb=19.8, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=28.2, disk_gb=26.4, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=55.8, disk_gb=52.8, quality="lossless"),
        ],
        ollama_id="gemma3:27b",
        featured=True,
        license="Gemma",
    ),
    AIModel(
        id="gemma4-26b-a4b-it",
        name="Gemma 4 26B-A4B IT",
        provider="Google",
        family="Gemma",
        params="27B",
        params_billions=27,
        architecture="moe",
        context_length=262144,
        use_case=['chat', 'vision', 'reasoning'],
        description="Gemma 4 MoE instruct model (official)",
        min_ram_gb=15.1,
        recommended_ram_gb=25.1,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=9.1, disk_gb=8.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=12.6, disk_gb=11.6, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=14.3, disk_gb=15.6, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=17.8, disk_gb=16.5, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=21.2, disk_gb=21.1, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=28.2, disk_gb=25, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=55.8, disk_gb=52.8, quality="lossless"),
        ],
        active_params="4B active",
        moe_info={'numExperts': 26, 'activeExperts': 4, 'activeParameters': 4000000000},
        license="Gemma",
    ),
    AIModel(
        id="gemma4-26b-a4b",
        name="Gemma 4 26B-A4B",
        provider="Google",
        family="Gemma",
        params="27B",
        params_billions=27,
        architecture="moe",
        context_length=262144,
        use_case=['vision', 'reasoning'],
        description="Gemma 4 MoE base model (official)",
        min_ram_gb=15.1,
        recommended_ram_gb=25.1,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=9.1, disk_gb=8.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=12.6, disk_gb=11.6, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=14.3, disk_gb=13.2, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=17.8, disk_gb=16.5, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=21.2, disk_gb=19.8, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=28.2, disk_gb=26.4, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=55.8, disk_gb=52.8, quality="lossless"),
        ],
        active_params="4B active",
        moe_info={'numExperts': 26, 'activeExperts': 4, 'activeParameters': 4000000000},
        license="Gemma",
    ),
    AIModel(
        id="gemma4-31b-it",
        name="Gemma 4 31B IT",
        provider="Google",
        family="Gemma",
        params="33B",
        params_billions=33,
        architecture="dense",
        context_length=262144,
        use_case=['chat', 'vision', 'reasoning'],
        description="Gemma 4 flagship instruct model (official)",
        min_ram_gb=18.4,
        recommended_ram_gb=30.7,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=11.1, disk_gb=10.1, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=15.3, disk_gb=14.1, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=17.4, disk_gb=17.4, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=21.6, disk_gb=20.2, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=25.9, disk_gb=23.5, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=34.3, disk_gb=30.4, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=68.1, disk_gb=64.5, quality="lossless"),
        ],
        license="Gemma",
    ),
]
