from .core import AIModel, Quantization

MODELS = [
    AIModel(
        id="gpt-oss-20b",
        name="GPT-OSS 20B",
        provider="OpenAI",
        family="GPT-OSS",
        params="21B",
        params_billions=21,
        architecture="moe",
        context_length=131072,
        use_case=['chat', 'reasoning', 'code'],
        description="OpenAI's open-weight MoE with configurable reasoning",
        min_ram_gb=11.7,
        recommended_ram_gb=19.6,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=7.2, disk_gb=6.4, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=9.9, disk_gb=9.0, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=11.3, disk_gb=10.3, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=13.9, disk_gb=12.8, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=16.6, disk_gb=15.4, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=22.0, disk_gb=20.5, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=43.5, disk_gb=41.1, quality="lossless"),
        ],
        active_params="3.6B active",
        moe_info={'numExperts': 16, 'activeExperts': 2, 'activeParameters': 3600000000},
        ollama_id="gpt-oss:20b",
        featured=True,
        license="Apache 2.0",
    ),
    AIModel(
        id="gpt-oss-120b",
        name="GPT-OSS 120B",
        provider="OpenAI",
        family="GPT-OSS",
        params="117B",
        params_billions=117,
        architecture="moe",
        context_length=131072,
        use_case=['chat', 'reasoning', 'code'],
        description="OpenAI's flagship open-weight MoE — 52.6% SWE-bench",
        min_ram_gb=65.4,
        recommended_ram_gb=109.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=38.0, disk_gb=35.8, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=52.9, disk_gb=50.1, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=60.4, disk_gb=57.2, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=75.4, disk_gb=71.5, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=90.4, disk_gb=85.8, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=120.4, disk_gb=114.4, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=240.2, disk_gb=228.8, quality="lossless"),
        ],
        active_params="5.1B active",
        moe_info={'numExperts': 16, 'activeExperts': 2, 'activeParameters': 5100000000},
        ollama_id="gpt-oss:120b",
        featured=True,
        license="Apache 2.0",
    ),
]
