from .core import AIModel, Quantization

MODELS = [
    AIModel(
        id="llama4-maverick-17b-128e",
        name="Llama 4 Maverick 17B-128E",
        provider="Meta",
        family="Llama",
        params="400B",
        params_billions=400,
        architecture="moe",
        context_length=1048576,
        use_case=['chat', 'vision', 'reasoning', 'code'],
        description="Multimodal MoE with 128 experts — 17B active, 1M context",
        min_ram_gb=223.5,
        recommended_ram_gb=372.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=128.6, disk_gb=122.2, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=179.8, disk_gb=171.1, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=205.4, disk_gb=195.6, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=256.6, disk_gb=244.5, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=307.8, disk_gb=293.4, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=410.3, disk_gb=391.2, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=820.1, disk_gb=782.3, quality="lossless"),
        ],
        active_params="17B active",
        moe_info={'numExperts': 128, 'activeExperts': 1, 'activeParameters': 17000000000},
        ollama_id="llama4:maverick",
        license="Llama 4 Community",
    ),
    AIModel(
        id="llama3.1-405b",
        name="Llama 3.1 405B",
        provider="Meta",
        family="Llama",
        params="405B",
        params_billions=405,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'reasoning', 'code'],
        description="Largest open-weight dense model by Meta",
        min_ram_gb=226.3,
        recommended_ram_gb=377.2,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=130.2, disk_gb=123.8, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=182.0, disk_gb=173.3, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=208.0, disk_gb=198.0, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=259.8, disk_gb=247.5, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=311.7, disk_gb=297.0, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=415.4, disk_gb=396.0, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=830.3, disk_gb=792.1, quality="lossless"),
        ],
        ollama_id="llama3.1:405b",
        license="Llama 3.1 Community",
    ),
]
