from .core import AIModel, Quantization

MODELS = [
    AIModel(
        id="llama3.2-1b",
        name="Llama 3.2 1B",
        provider="Meta",
        family="Llama",
        params="1B",
        params_billions=1,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'edge'],
        description="Meta's smallest Llama for edge devices",
        min_ram_gb=1.0,
        recommended_ram_gb=2.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=0.8, disk_gb=0.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=0.9, disk_gb=0.4, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=1.0, disk_gb=0.5, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=1.1, disk_gb=0.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=1.3, disk_gb=0.7, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=1.5, disk_gb=1.0, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=2.5, disk_gb=2.0, quality="lossless"),
        ],
        ollama_id="llama3.2:1b",
        license="Llama 3.2 Community",
    ),
    AIModel(
        id="tinyllama-1.1b",
        name="TinyLlama 1.1B",
        provider="Community",
        family="Llama",
        params="1.1B",
        params_billions=1.1,
        architecture="dense",
        context_length=2048,
        use_case=['chat', 'edge'],
        description="Ultralight model for constrained devices",
        min_ram_gb=1.0,
        recommended_ram_gb=2.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=0.9, disk_gb=0.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=1.0, disk_gb=0.5, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=1.1, disk_gb=0.5, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=1.2, disk_gb=0.7, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=1.3, disk_gb=0.8, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=1.6, disk_gb=1.1, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=2.8, disk_gb=2.2, quality="lossless"),
        ],
        ollama_id="tinyllama",
        license="Apache 2.0",
    ),
    AIModel(
        id="llama3.2-3b",
        name="Llama 3.2 3B",
        provider="Meta",
        family="Llama",
        params="3B",
        params_billions=3,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'code'],
        description="Lightweight Llama for mobile and edge",
        min_ram_gb=1.7,
        recommended_ram_gb=2.8,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=1.5, disk_gb=0.9, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=1.8, disk_gb=1.3, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=2.0, disk_gb=1.5, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=2.4, disk_gb=1.8, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=2.8, disk_gb=2.2, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=3.6, disk_gb=2.9, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=6.6, disk_gb=5.9, quality="lossless"),
        ],
        ollama_id="llama3.2:3b",
        license="Llama 3.2 Community",
    ),
    AIModel(
        id="llama3.1-8b",
        name="Llama 3.1 8B",
        provider="Meta",
        family="Llama",
        params="8B",
        params_billions=8,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'code', 'reasoning'],
        description="Meta's versatile 8B — great quality/speed ratio",
        min_ram_gb=4.5,
        recommended_ram_gb=7.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=3.1, disk_gb=2.4, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=4.1, disk_gb=3.4, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=4.6, disk_gb=3.9, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=5.6, disk_gb=4.9, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=6.6, disk_gb=5.9, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=8.7, disk_gb=7.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=16.9, disk_gb=15.6, quality="lossless"),
        ],
        ollama_id="llama3.1:8b",
        featured=True,
        license="Llama 3.1 Community",
    ),
    AIModel(
        id="llama3.2-11b-vision",
        name="Llama 3.2 11B Vision",
        provider="Meta",
        family="Llama",
        params="11B",
        params_billions=11,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'vision'],
        description="Multimodal vision and text model",
        min_ram_gb=6.1,
        recommended_ram_gb=10.2,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=4.0, disk_gb=3.4, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=5.4, disk_gb=4.7, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=6.1, disk_gb=5.4, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=7.5, disk_gb=6.7, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=9.0, disk_gb=8.1, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=11.8, disk_gb=10.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=23.0, disk_gb=21.5, quality="lossless"),
        ],
        ollama_id="llama3.2-vision:11b",
        license="Llama 3.2 Community",
    ),
    AIModel(
        id="llama4-scout-17b",
        name="Llama 4 Scout 17B",
        provider="Meta",
        family="Llama",
        params="109B",
        params_billions=109,
        architecture="moe",
        context_length=131072,
        use_case=['chat', 'vision', 'reasoning'],
        description="MoE with 16 experts, 17B active params",
        min_ram_gb=60.9,
        recommended_ram_gb=101.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=35.4, disk_gb=33.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=49.4, disk_gb=46.6, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=56.3, disk_gb=53.3, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=70.3, disk_gb=66.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=84.2, disk_gb=79.9, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=112.2, disk_gb=106.6, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=223.8, disk_gb=213.2, quality="lossless"),
        ],
        active_params="17B active",
        moe_info={'numExperts': 16, 'activeExperts': 1, 'activeParameters': 17000000000},
        ollama_id="llama4:scout",
        featured=True,
        license="Llama 4 Community",
    ),
    AIModel(
        id="llama3.3-70b",
        name="Llama 3.3 70B",
        provider="Meta",
        family="Llama",
        params="70B",
        params_billions=70,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'reasoning', 'code'],
        description="Best open model at 70B class",
        min_ram_gb=39.1,
        recommended_ram_gb=65.2,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=22.9, disk_gb=21.4, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=31.9, disk_gb=29.9, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=36.4, disk_gb=34.2, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=45.3, disk_gb=42.8, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=54.3, disk_gb=51.3, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=72.2, disk_gb=68.5, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=143.9, disk_gb=136.9, quality="lossless"),
        ],
        ollama_id="llama3.3:70b",
        featured=True,
        license="Llama 3.3 Community",
    ),
]
