from .core import AIModel, Quantization

MODELS = [
    AIModel(
        id="mistral-7b",
        name="Mistral 7B v0.3",
        provider="Mistral AI",
        family="Mistral",
        params="7B",
        params_billions=7,
        architecture="dense",
        context_length=32768,
        use_case=['chat', 'reasoning'],
        description="High-quality 7B with sliding window attention",
        min_ram_gb=3.9,
        recommended_ram_gb=6.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=2.7, disk_gb=2.1, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=3.6, disk_gb=3.0, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=4.1, disk_gb=3.4, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=5.0, disk_gb=4.3, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=5.9, disk_gb=5.1, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=7.7, disk_gb=6.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=14.8, disk_gb=13.7, quality="lossless"),
        ],
        ollama_id="mistral",
        license="Apache 2.0",
    ),
    AIModel(
        id="ministral-8b",
        name="Ministral 8B",
        provider="Mistral AI",
        family="Mistral",
        params="8B",
        params_billions=8,
        architecture="dense",
        context_length=32768,
        use_case=['chat'],
        description="Mistral's efficient 8B model",
        min_ram_gb=4.5,
        recommended_ram_gb=7.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=3.1, disk_gb=2.4, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=4.1, disk_gb=3.4, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=4.6, disk_gb=3.9, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=5.6, disk_gb=4.9, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=6.6, disk_gb=5.9, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=8.7, disk_gb=7.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=16.9, disk_gb=15.6, quality="lossless"),
        ],
        ollama_id="ministral-3:8b",
        license="MRL",
    ),
    AIModel(
        id="mistral-nemo-12b",
        name="Mistral Nemo 12B",
        provider="Mistral AI",
        family="Mistral",
        params="12B",
        params_billions=12,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'multilingual'],
        description="Multilingual 12B with 128K context",
        min_ram_gb=6.7,
        recommended_ram_gb=11.2,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=4.3, disk_gb=3.7, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=5.9, disk_gb=5.1, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=6.6, disk_gb=5.9, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=8.2, disk_gb=7.3, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=9.7, disk_gb=8.8, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=12.8, disk_gb=11.7, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=25.1, disk_gb=23.5, quality="lossless"),
        ],
        ollama_id="mistral-nemo",
        license="Apache 2.0",
    ),
    AIModel(
        id="devstral-small-2-24b",
        name="Devstral Small 2 24B",
        provider="Mistral AI",
        family="Mistral",
        params="24B",
        params_billions=24,
        architecture="dense",
        context_length=262144,
        use_case=['code'],
        description="Coding-focused model with 256K context — 68% SWE-bench",
        min_ram_gb=13.4,
        recommended_ram_gb=22.4,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=8.2, disk_gb=7.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=11.3, disk_gb=10.3, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=12.8, disk_gb=11.7, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=15.9, disk_gb=14.7, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=18.9, disk_gb=17.6, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=25.1, disk_gb=23.5, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=49.7, disk_gb=46.9, quality="lossless"),
        ],
        ollama_id="devstral-small-2",
        license="Apache 2.0",
    ),
    AIModel(
        id="mistral-small-24b",
        name="Mistral Small 3.1 24B",
        provider="Mistral AI",
        family="Mistral",
        params="24B",
        params_billions=24,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'vision', 'code'],
        description="Multimodal Mistral with vision support",
        min_ram_gb=13.4,
        recommended_ram_gb=22.4,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=8.2, disk_gb=7.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=11.3, disk_gb=10.3, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=12.8, disk_gb=11.7, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=15.9, disk_gb=14.7, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=18.9, disk_gb=17.6, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=25.1, disk_gb=23.5, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=49.7, disk_gb=46.9, quality="lossless"),
        ],
        ollama_id="mistral-small",
        featured=True,
        license="Apache 2.0",
    ),
    AIModel(
        id="mixtral-8x7b",
        name="Mixtral 8x7B",
        provider="Mistral AI",
        family="Mistral",
        params="47B",
        params_billions=47,
        architecture="moe",
        context_length=32768,
        use_case=['chat', 'code'],
        description="MoE with 12.9B active params",
        min_ram_gb=26.3,
        recommended_ram_gb=43.8,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=15.5, disk_gb=14.4, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=21.6, disk_gb=20.1, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=24.6, disk_gb=23.0, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=30.6, disk_gb=28.7, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=36.6, disk_gb=34.5, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=48.6, disk_gb=46.0, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=96.8, disk_gb=91.9, quality="lossless"),
        ],
        active_params="12.9B active",
        moe_info={'numExperts': 8, 'activeExperts': 2, 'activeParameters': 12900000000},
        ollama_id="mixtral:8x7b",
        license="Apache 2.0",
    ),
    AIModel(
        id="devstral-2-123b",
        name="Devstral 2 123B",
        provider="Mistral AI",
        family="Mistral",
        params="123B",
        params_billions=123,
        architecture="dense",
        context_length=262144,
        use_case=['code'],
        description="Dense 123B coding model — 72.2% SWE-bench Verified",
        min_ram_gb=68.7,
        recommended_ram_gb=114.6,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=39.9, disk_gb=37.6, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=55.6, disk_gb=52.6, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=63.5, disk_gb=60.1, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=79.3, disk_gb=75.2, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=95.0, disk_gb=90.2, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=126.5, disk_gb=120.3, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=252.5, disk_gb=240.6, quality="lossless"),
        ],
        ollama_id="devstral-2",
        featured=True,
        license="MRL",
    ),
]
