from .core import AIModel, Quantization

MODELS = [
    AIModel(
        id="nemotron-nano-9b",
        name="Nemotron Nano 9B v2",
        provider="NVIDIA",
        family="Nemotron",
        params="9B",
        params_billions=9,
        architecture="dense",
        context_length=131072,
        use_case=['reasoning'],
        description="Hybrid Mamba2 architecture for reasoning",
        min_ram_gb=5.0,
        recommended_ram_gb=8.4,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=3.4, disk_gb=2.8, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=4.5, disk_gb=3.9, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=5.1, disk_gb=4.4, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=6.3, disk_gb=5.5, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=7.4, disk_gb=6.6, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=9.7, disk_gb=8.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=18.9, disk_gb=17.6, quality="lossless"),
        ],
        license="NVIDIA Open",
    ),
    AIModel(
        id="nemotron-nano-30b",
        name="Nemotron 3 Nano 30B",
        provider="NVIDIA",
        family="Nemotron",
        params="30B",
        params_billions=30,
        architecture="moe",
        context_length=1048576,
        use_case=['chat', 'reasoning'],
        description="MoE with 1M context and 3B active",
        min_ram_gb=16.8,
        recommended_ram_gb=27.9,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=10.1, disk_gb=9.2, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=13.9, disk_gb=12.8, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=15.9, disk_gb=14.7, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=19.7, disk_gb=18.3, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=23.6, disk_gb=22.0, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=31.2, disk_gb=29.3, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=62.0, disk_gb=58.7, quality="lossless"),
        ],
        active_params="3B active",
        moe_info={'numExperts': 128, 'activeExperts': 6, 'activeParameters': 3000000000},
        ollama_id="nemotron-3-nano:30b",
        license="NVIDIA Open",
    ),
]
