from .core import AIModel, Quantization

MODELS = [
    AIModel(
        id="phi-3.5-mini",
        name="Phi-3.5 Mini",
        provider="Microsoft",
        family="Phi",
        params="3.8B",
        params_billions=3.8,
        architecture="dense",
        context_length=131072,
        use_case=['reasoning', 'code', 'chat'],
        description="Microsoft's efficient small model with long context",
        min_ram_gb=2.1,
        recommended_ram_gb=3.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=1.7, disk_gb=1.2, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=2.2, disk_gb=1.6, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=2.4, disk_gb=1.9, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=2.9, disk_gb=2.3, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=3.4, disk_gb=2.8, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=4.4, disk_gb=3.7, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=8.3, disk_gb=7.4, quality="lossless"),
        ],
        ollama_id="phi3.5",
        license="MIT",
    ),
    AIModel(
        id="phi-4-mini-reasoning",
        name="Phi-4 Mini Reasoning",
        provider="Microsoft",
        family="Phi",
        params="3.8B",
        params_billions=3.8,
        architecture="dense",
        context_length=16384,
        use_case=['reasoning'],
        description="Lightweight reasoning model",
        min_ram_gb=2.1,
        recommended_ram_gb=3.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=1.7, disk_gb=1.2, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=2.2, disk_gb=1.6, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=2.4, disk_gb=1.9, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=2.9, disk_gb=2.3, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=3.4, disk_gb=2.8, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=4.4, disk_gb=3.7, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=8.3, disk_gb=7.4, quality="lossless"),
        ],
        ollama_id="phi4-mini-reasoning",
        license="MIT",
    ),
    AIModel(
        id="phi-4-14b",
        name="Phi-4 14B",
        provider="Microsoft",
        family="Phi",
        params="14B",
        params_billions=14,
        architecture="dense",
        context_length=16384,
        use_case=['reasoning', 'code'],
        description="Microsoft's reasoning-focused model",
        min_ram_gb=7.8,
        recommended_ram_gb=13.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=5.0, disk_gb=4.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=6.8, disk_gb=6.0, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=7.7, disk_gb=6.8, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=9.5, disk_gb=8.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=11.3, disk_gb=10.3, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=14.8, disk_gb=13.7, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=29.2, disk_gb=27.4, quality="lossless"),
        ],
        ollama_id="phi4",
        featured=True,
        license="MIT",
    ),
]
