from .core import AIModel, Quantization

MODELS = [
    AIModel(
        id="qwen3-30b-a3b",
        name="Qwen 3 30B-A3B",
        provider="Alibaba",
        family="Qwen",
        params="30B",
        params_billions=30,
        architecture="moe",
        context_length=131072,
        use_case=['chat', 'reasoning'],
        description="MoE with only 3.3B active — extremely efficient",
        min_ram_gb=16.8,
        recommended_ram_gb=27.9,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=10.1, disk_gb=9.2, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=13.9, disk_gb=12.8, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=15.9, disk_gb=14.7, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=19.7, disk_gb=18.3, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=23.6, disk_gb=22.0, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=31.2, disk_gb=29.3, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=62.0, disk_gb=58.7, quality="lossless"),
        ],
        active_params="3.3B active",
        moe_info={'numExperts': 128, 'activeExperts': 8, 'activeParameters': 3300000000},
        ollama_id="qwen3:30b-a3b",
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen2.5-32b",
        name="Qwen 2.5 32B",
        provider="Alibaba",
        family="Qwen",
        params="32B",
        params_billions=32,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'multilingual', 'reasoning'],
        description="High-quality reasoning and multilingual",
        min_ram_gb=17.9,
        recommended_ram_gb=29.8,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=10.7, disk_gb=9.8, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=14.8, disk_gb=13.7, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=16.9, disk_gb=15.6, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=21.0, disk_gb=19.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=25.1, disk_gb=23.5, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=33.3, disk_gb=31.3, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=66.1, disk_gb=62.6, quality="lossless"),
        ],
        ollama_id="qwen2.5:32b",
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen2.5-coder-32b",
        name="Qwen 2.5 Coder 32B",
        provider="Alibaba",
        family="Qwen",
        params="32B",
        params_billions=32,
        architecture="dense",
        context_length=131072,
        use_case=['code'],
        description="Best open-source coding model at release",
        min_ram_gb=17.9,
        recommended_ram_gb=29.8,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=10.7, disk_gb=9.8, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=14.8, disk_gb=13.7, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=16.9, disk_gb=15.6, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=21.0, disk_gb=19.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=25.1, disk_gb=23.5, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=33.3, disk_gb=31.3, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=66.1, disk_gb=62.6, quality="lossless"),
        ],
        ollama_id="qwen2.5-coder:32b",
        featured=True,
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen3-32b",
        name="Qwen 3 32B",
        provider="Alibaba",
        family="Qwen",
        params="32B",
        params_billions=32,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'code', 'reasoning'],
        description="Qwen 3 flagship dense model",
        min_ram_gb=17.9,
        recommended_ram_gb=29.8,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=10.7, disk_gb=9.8, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=14.8, disk_gb=13.7, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=16.9, disk_gb=15.6, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=21.0, disk_gb=19.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=25.1, disk_gb=23.5, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=33.3, disk_gb=31.3, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=66.1, disk_gb=62.6, quality="lossless"),
        ],
        ollama_id="qwen3:32b",
        featured=True,
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen3.5-35b-a3b",
        name="Qwen 3.5 35B-A3B",
        provider="Alibaba",
        family="Qwen",
        params="35B",
        params_billions=35,
        architecture="moe",
        context_length=262144,
        use_case=['chat', 'vision'],
        description="Efficient multimodal MoE with 3B active",
        min_ram_gb=19.6,
        recommended_ram_gb=32.6,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=11.7, disk_gb=10.7, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=16.2, disk_gb=15.0, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=18.4, disk_gb=19.7, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=22.9, disk_gb=21.4, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=27.4, disk_gb=26.6, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=36.4, disk_gb=34.4, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=72.2, disk_gb=68.5, quality="lossless"),
        ],
        active_params="3B active",
        moe_info={'numExperts': 256, 'activeExperts': 8, 'activeParameters': 3000000000},
        ollama_id="qwen3.5:35b-a3b",
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen2.5-72b",
        name="Qwen 2.5 72B",
        provider="Alibaba",
        family="Qwen",
        params="72B",
        params_billions=72,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'multilingual', 'reasoning', 'code'],
        description="Alibaba's flagship open model",
        min_ram_gb=40.2,
        recommended_ram_gb=67.1,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=23.6, disk_gb=22.0, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=32.8, disk_gb=30.8, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=37.4, disk_gb=35.2, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=46.6, disk_gb=44.0, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=55.8, disk_gb=52.8, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=74.3, disk_gb=70.4, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=148.0, disk_gb=140.8, quality="lossless"),
        ],
        ollama_id="qwen2.5:72b",
        license="Qwen",
    ),
    AIModel(
        id="qwen3.5-122b-a10b",
        name="Qwen 3.5 122B-A10B",
        provider="Alibaba",
        family="Qwen",
        params="122B",
        params_billions=122,
        architecture="moe",
        context_length=262144,
        use_case=['chat', 'vision', 'reasoning'],
        description="Large multimodal MoE",
        min_ram_gb=68.2,
        recommended_ram_gb=113.6,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=39.6, disk_gb=37.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=55.2, disk_gb=52.2, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=63.0, disk_gb=37.3, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=78.6, disk_gb=74.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=94.2, disk_gb=37.1, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=125.5, disk_gb=37.2, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=250.5, disk_gb=238.6, quality="lossless"),
        ],
        active_params="10B active",
        moe_info={'numExperts': 256, 'activeExperts': 8, 'activeParameters': 10000000000},
        ollama_id="qwen3.5:122b-a10b",
        license="Apache 2.0",
    ),
]
