from .core import AIModel, Quantization

MODELS = [
    AIModel(
        id="qwen2.5-7b",
        name="Qwen 2.5 7B",
        provider="Alibaba",
        family="Qwen",
        params="7B",
        params_billions=7,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'multilingual', 'code'],
        description="Strong multilingual and coding capabilities",
        min_ram_gb=3.9,
        recommended_ram_gb=6.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=2.7, disk_gb=2.1, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=3.6, disk_gb=3.0, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=4.1, disk_gb=3.4, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=5.0, disk_gb=4.3, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=5.9, disk_gb=5.1, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=7.7, disk_gb=6.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=14.8, disk_gb=13.7, quality="lossless"),
        ],
        ollama_id="qwen2.5:7b",
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen2.5-coder-7b",
        name="Qwen 2.5 Coder 7B",
        provider="Alibaba",
        family="Qwen",
        params="7B",
        params_billions=7,
        architecture="dense",
        context_length=131072,
        use_case=['code'],
        description="Dedicated coding model",
        min_ram_gb=3.9,
        recommended_ram_gb=6.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=2.7, disk_gb=2.1, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=3.6, disk_gb=3.0, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=4.1, disk_gb=3.4, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=5.0, disk_gb=4.3, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=5.9, disk_gb=5.1, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=7.7, disk_gb=6.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=14.8, disk_gb=13.7, quality="lossless"),
        ],
        ollama_id="qwen2.5-coder:7b",
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen3-8b",
        name="Qwen 3 8B",
        provider="Alibaba",
        family="Qwen",
        params="8B",
        params_billions=8,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'code', 'reasoning'],
        description="Qwen 3 with thinking mode support",
        min_ram_gb=4.5,
        recommended_ram_gb=7.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=3.1, disk_gb=2.4, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=4.1, disk_gb=3.4, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=4.6, disk_gb=3.9, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=5.6, disk_gb=4.9, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=6.6, disk_gb=5.9, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=8.7, disk_gb=7.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=16.9, disk_gb=15.6, quality="lossless"),
        ],
        ollama_id="qwen3:8b",
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen3.5-9b",
        name="Qwen 3.5 9B",
        provider="Alibaba",
        family="Qwen",
        params="9B",
        params_billions=9,
        architecture="dense",
        context_length=32768,
        use_case=['chat', 'vision'],
        description="Multimodal Qwen 3.5 mid-size",
        min_ram_gb=5.0,
        recommended_ram_gb=8.4,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=3.4, disk_gb=2.8, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=4.5, disk_gb=3.9, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=5.1, disk_gb=5.2, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=6.3, disk_gb=5.5, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=7.4, disk_gb=6.9, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=9.7, disk_gb=8.9, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=18.9, disk_gb=17.6, quality="lossless"),
        ],
        ollama_id="qwen3.5:9b",
        featured=True,
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen2.5-14b",
        name="Qwen 2.5 14B",
        provider="Alibaba",
        family="Qwen",
        params="14B",
        params_billions=14,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'multilingual', 'reasoning'],
        description="Excellent quality for its size class",
        min_ram_gb=7.8,
        recommended_ram_gb=13.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=5.0, disk_gb=4.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=6.8, disk_gb=6.0, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=7.7, disk_gb=6.8, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=9.5, disk_gb=8.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=11.3, disk_gb=10.3, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=14.8, disk_gb=13.7, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=29.2, disk_gb=27.4, quality="lossless"),
        ],
        ollama_id="qwen2.5:14b",
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen3-14b",
        name="Qwen 3 14B",
        provider="Alibaba",
        family="Qwen",
        params="14B",
        params_billions=14,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'code', 'reasoning'],
        description="Strong all-rounder with thinking mode",
        min_ram_gb=7.8,
        recommended_ram_gb=13.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=5.0, disk_gb=4.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=6.8, disk_gb=6.0, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=7.7, disk_gb=6.8, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=9.5, disk_gb=8.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=11.3, disk_gb=10.3, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=14.8, disk_gb=13.7, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=29.2, disk_gb=27.4, quality="lossless"),
        ],
        ollama_id="qwen3:14b",
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen3.5-27b",
        name="Qwen 3.5 27B",
        provider="Alibaba",
        family="Qwen",
        params="27.8B",
        params_billions=27.8,
        architecture="dense",
        context_length=262144,
        use_case=['chat', 'vision', 'reasoning'],
        description="Flagship native multimodal Qwen 3.5",
        min_ram_gb=15.5,
        recommended_ram_gb=25.9,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=9.4, disk_gb=8.5, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=13.0, disk_gb=11.9, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=14.7, disk_gb=15.4, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=18.3, disk_gb=17.0, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=21.9, disk_gb=20.6, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=29.0, disk_gb=26.6, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=57.5, disk_gb=54.4, quality="lossless"),
        ],
        ollama_id="qwen3.5:27b",
        license="Apache 2.0",
    ),
]
