from .core import AIModel, Quantization

MODELS = [
    AIModel(
        id="qwen3-235b-a22b",
        name="Qwen 3 235B-A22B",
        provider="Alibaba",
        family="Qwen",
        params="235B",
        params_billions=235,
        architecture="moe",
        context_length=131072,
        use_case=['chat', 'code', 'reasoning'],
        description="Massive MoE with 22B active — frontier quality",
        min_ram_gb=131.3,
        recommended_ram_gb=218.9,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=75.7, disk_gb=71.8, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=105.8, disk_gb=100.5, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=120.9, disk_gb=114.9, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=151.0, disk_gb=143.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=181.1, disk_gb=172.4, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=241.2, disk_gb=229.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=482.0, disk_gb=459.6, quality="lossless"),
        ],
        active_params="22B active",
        moe_info={'numExperts': 128, 'activeExperts': 8, 'activeParameters': 22000000000},
        ollama_id="qwen3:235b-a22b",
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen3.5-397b-a17b",
        name="Qwen 3.5 397B-A17B",
        provider="Alibaba",
        family="Qwen",
        params="397B",
        params_billions=397,
        architecture="moe",
        context_length=262144,
        use_case=['chat', 'vision', 'reasoning', 'code'],
        description="Largest multimodal Qwen 3.5 MoE",
        min_ram_gb=221.8,
        recommended_ram_gb=369.7,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=127.6, disk_gb=121.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=178.4, disk_gb=169.8, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=203.9, disk_gb=194.1, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=254.7, disk_gb=242.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=305.5, disk_gb=291.2, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=407.2, disk_gb=388.2, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=813.9, disk_gb=776.4, quality="lossless"),
        ],
        active_params="17B active",
        moe_info={'numExperts': 256, 'activeExperts': 8, 'activeParameters': 17000000000},
        ollama_id="qwen3.5:397b-cloud",
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen3-coder-480b",
        name="Qwen 3 Coder 480B",
        provider="Alibaba",
        family="Qwen",
        params="480B",
        params_billions=480,
        architecture="moe",
        context_length=262144,
        use_case=['code'],
        description="Largest open coding MoE — 35B active",
        min_ram_gb=268.2,
        recommended_ram_gb=447.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=154.2, disk_gb=146.7, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=215.6, disk_gb=205.4, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=246.4, disk_gb=234.7, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=307.8, disk_gb=293.4, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=369.3, disk_gb=352.0, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=492.2, disk_gb=469.4, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=984.0, disk_gb=938.8, quality="lossless"),
        ],
        active_params="35B active",
        moe_info={'numExperts': 128, 'activeExperts': 8, 'activeParameters': 35000000000},
        ollama_id="qwen3-coder:480b",
        license="Apache 2.0",
    ),
]
