from .core import AIModel, Quantization

MODELS = [
    AIModel(
        id="qwen3.5-0.8b",
        name="Qwen 3.5 0.8B",
        provider="Alibaba",
        family="Qwen",
        params="0.8B",
        params_billions=0.8,
        architecture="dense",
        context_length=32768,
        use_case=['chat', 'edge'],
        description="Ultra-tiny model for embedded and edge",
        min_ram_gb=1.0,
        recommended_ram_gb=2.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=0.8, disk_gb=0.2, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=0.9, disk_gb=0.3, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=0.9, disk_gb=0.5, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=1.0, disk_gb=0.5, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=1.1, disk_gb=0.6, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=1.3, disk_gb=0.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=2.1, disk_gb=1.6, quality="lossless"),
        ],
        ollama_id="qwen3.5:0.8b",
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen3-0.6b",
        name="Qwen 3 0.6B",
        provider="Alibaba",
        family="Qwen",
        params="0.6B",
        params_billions=0.6,
        architecture="dense",
        context_length=32768,
        use_case=['chat', 'edge'],
        description="Ultra-light Qwen 3 model for constrained devices",
        min_ram_gb=1.0,
        recommended_ram_gb=2.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=0.7, disk_gb=0.2, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=0.8, disk_gb=0.3, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=0.8, disk_gb=0.5, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=0.9, disk_gb=0.4, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=1.0, disk_gb=0.6, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=1.1, disk_gb=0.7, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=1.7, disk_gb=1.2, quality="lossless"),
        ],
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen2.5-coder-1.5b",
        name="Qwen 2.5 Coder 1.5B",
        provider="Alibaba",
        family="Qwen",
        params="1.5B",
        params_billions=1.5,
        architecture="dense",
        context_length=32768,
        use_case=['code'],
        description="Ultra-lightweight coding model",
        min_ram_gb=1.0,
        recommended_ram_gb=2.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=1.0, disk_gb=0.5, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=1.2, disk_gb=0.6, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=1.3, disk_gb=0.7, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=1.5, disk_gb=0.9, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=1.7, disk_gb=1.1, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=2.0, disk_gb=1.5, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=3.6, disk_gb=2.9, quality="lossless"),
        ],
        ollama_id="qwen2.5-coder:1.5b",
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen3-1.7b",
        name="Qwen 3 1.7B",
        provider="Alibaba",
        family="Qwen",
        params="1.7B",
        params_billions=1.7,
        architecture="dense",
        context_length=32768,
        use_case=['chat', 'multilingual'],
        description="Compact multilingual Qwen 3",
        min_ram_gb=1.0,
        recommended_ram_gb=2.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=1.0, disk_gb=0.5, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=1.3, disk_gb=0.7, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=1.4, disk_gb=0.8, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=1.6, disk_gb=1.0, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=1.8, disk_gb=1.2, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=2.2, disk_gb=1.7, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=4.0, disk_gb=3.3, quality="lossless"),
        ],
        ollama_id="qwen3:1.7b",
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen3.5-2b",
        name="Qwen 3.5 2B",
        provider="Alibaba",
        family="Qwen",
        params="2B",
        params_billions=2,
        architecture="dense",
        context_length=32768,
        use_case=['chat', 'multilingual'],
        description="Small multimodal Qwen 3.5",
        min_ram_gb=1.1,
        recommended_ram_gb=2.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=1.1, disk_gb=0.6, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=1.4, disk_gb=0.9, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=1.5, disk_gb=1.2, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=1.8, disk_gb=1.2, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=2.0, disk_gb=1.4, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=2.5, disk_gb=1.9, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=4.6, disk_gb=3.9, quality="lossless"),
        ],
        ollama_id="qwen3.5:2b",
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen3-4b",
        name="Qwen 3 4B",
        provider="Alibaba",
        family="Qwen",
        params="4B",
        params_billions=4,
        architecture="dense",
        context_length=32768,
        use_case=['chat', 'code'],
        description="Compact Qwen 3 for general tasks",
        min_ram_gb=2.2,
        recommended_ram_gb=3.7,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=1.8, disk_gb=1.2, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=2.3, disk_gb=1.7, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=2.5, disk_gb=2.0, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=3.1, disk_gb=2.4, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=3.6, disk_gb=2.9, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=4.6, disk_gb=3.9, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=8.7, disk_gb=7.8, quality="lossless"),
        ],
        ollama_id="qwen3:4b",
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen3.5-4b",
        name="Qwen 3.5 4B",
        provider="Alibaba",
        family="Qwen",
        params="4B",
        params_billions=4,
        architecture="dense",
        context_length=32768,
        use_case=['chat', 'multilingual'],
        description="Small multimodal Qwen 3.5",
        min_ram_gb=2.2,
        recommended_ram_gb=3.7,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=1.8, disk_gb=1.2, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=2.3, disk_gb=1.7, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=2.5, disk_gb=2.5, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=3.1, disk_gb=2.4, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=3.6, disk_gb=3.2, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=4.6, disk_gb=4.2, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=8.7, disk_gb=7.8, quality="lossless"),
        ],
        ollama_id="qwen3.5:4b",
        license="Apache 2.0",
    ),
]
