from dataclasses import dataclass
from typing import Optional, List, Dict, Any

@dataclass(frozen=True)
class Quantization:
    name: str
    bits: int
    vram_gb: float
    disk_gb: float
    quality: str

@dataclass(frozen=True)
class AIModel:
    id: str
    name: str
    provider: str
    family: str
    params: str
    params_billions: float
    architecture: str
    context_length: int
    use_case: List[str]
    description: str
    min_ram_gb: float
    recommended_ram_gb: float
    quants: List[Quantization]
    active_params: Optional[str] = None
    moe_info: Optional[Dict[str, Any]] = None
    ollama_id: Optional[str] = None
    featured: bool = False
    license: Optional[str] = None

MODELS: List[AIModel] = [
    AIModel(
        id="qwen3.5-0.8b",
        name="Qwen 3.5 0.8B",
        provider="Alibaba",
        family="Qwen",
        params="0.8B",
        params_billions=0.8,
        architecture="dense",
        context_length=32768,
        use_case=['chat', 'edge'],
        description="Ultra-tiny model for embedded and edge",
        min_ram_gb=1.0,
        recommended_ram_gb=2.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=0.8, disk_gb=0.2, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=0.9, disk_gb=0.3, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=0.9, disk_gb=0.5, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=1.0, disk_gb=0.5, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=1.1, disk_gb=0.6, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=1.3, disk_gb=0.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=2.1, disk_gb=1.6, quality="lossless"),
        ],
        ollama_id="qwen3.5:0.8b",
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen3-0.6b",
        name="Qwen 3 0.6B",
        provider="Alibaba",
        family="Qwen",
        params="0.6B",
        params_billions=0.6,
        architecture="dense",
        context_length=32768,
        use_case=['chat', 'edge'],
        description="Ultra-light Qwen 3 model for constrained devices",
        min_ram_gb=1.0,
        recommended_ram_gb=2.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=0.7, disk_gb=0.2, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=0.8, disk_gb=0.3, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=0.8, disk_gb=0.5, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=0.9, disk_gb=0.4, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=1.0, disk_gb=0.6, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=1.1, disk_gb=0.7, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=1.7, disk_gb=1.2, quality="lossless"),
        ],
        license="Apache 2.0",
    ),
    AIModel(
        id="llama3.2-1b",
        name="Llama 3.2 1B",
        provider="Meta",
        family="Llama",
        params="1B",
        params_billions=1,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'edge'],
        description="Meta's smallest Llama for edge devices",
        min_ram_gb=1.0,
        recommended_ram_gb=2.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=0.8, disk_gb=0.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=0.9, disk_gb=0.4, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=1.0, disk_gb=0.5, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=1.1, disk_gb=0.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=1.3, disk_gb=0.7, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=1.5, disk_gb=1.0, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=2.5, disk_gb=2.0, quality="lossless"),
        ],
        ollama_id="llama3.2:1b",
        license="Llama 3.2 Community",
    ),
    AIModel(
        id="gemma3-1b",
        name="Gemma 3 1B",
        provider="Google",
        family="Gemma",
        params="1B",
        params_billions=1,
        architecture="dense",
        context_length=32768,
        use_case=['chat', 'edge'],
        description="Google's tiny Gemma for on-device",
        min_ram_gb=1.0,
        recommended_ram_gb=2.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=0.8, disk_gb=0.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=0.9, disk_gb=0.4, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=1.0, disk_gb=0.5, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=1.1, disk_gb=0.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=1.3, disk_gb=0.7, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=1.5, disk_gb=1.0, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=2.5, disk_gb=2.0, quality="lossless"),
        ],
        ollama_id="gemma3:1b",
        license="Gemma",
    ),
    AIModel(
        id="tinyllama-1.1b",
        name="TinyLlama 1.1B",
        provider="Community",
        family="Llama",
        params="1.1B",
        params_billions=1.1,
        architecture="dense",
        context_length=2048,
        use_case=['chat', 'edge'],
        description="Ultralight model for constrained devices",
        min_ram_gb=1.0,
        recommended_ram_gb=2.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=0.9, disk_gb=0.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=1.0, disk_gb=0.5, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=1.1, disk_gb=0.5, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=1.2, disk_gb=0.7, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=1.3, disk_gb=0.8, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=1.6, disk_gb=1.1, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=2.8, disk_gb=2.2, quality="lossless"),
        ],
        ollama_id="tinyllama",
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen2.5-coder-1.5b",
        name="Qwen 2.5 Coder 1.5B",
        provider="Alibaba",
        family="Qwen",
        params="1.5B",
        params_billions=1.5,
        architecture="dense",
        context_length=32768,
        use_case=['code'],
        description="Ultra-lightweight coding model",
        min_ram_gb=1.0,
        recommended_ram_gb=2.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=1.0, disk_gb=0.5, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=1.2, disk_gb=0.6, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=1.3, disk_gb=0.7, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=1.5, disk_gb=0.9, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=1.7, disk_gb=1.1, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=2.0, disk_gb=1.5, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=3.6, disk_gb=2.9, quality="lossless"),
        ],
        ollama_id="qwen2.5-coder:1.5b",
        license="Apache 2.0",
    ),
    AIModel(
        id="deepseek-r1-1.5b",
        name="DeepSeek R1 1.5B",
        provider="DeepSeek",
        family="DeepSeek",
        params="1.5B",
        params_billions=1.5,
        architecture="dense",
        context_length=65536,
        use_case=['reasoning'],
        description="Tiny reasoning model distilled from R1",
        min_ram_gb=1.0,
        recommended_ram_gb=2.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=1.0, disk_gb=0.5, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=1.2, disk_gb=0.6, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=1.3, disk_gb=0.7, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=1.5, disk_gb=0.9, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=1.7, disk_gb=1.1, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=2.0, disk_gb=1.5, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=3.6, disk_gb=2.9, quality="lossless"),
        ],
        ollama_id="deepseek-r1:1.5b",
        license="MIT",
    ),
    AIModel(
        id="qwen3-1.7b",
        name="Qwen 3 1.7B",
        provider="Alibaba",
        family="Qwen",
        params="1.7B",
        params_billions=1.7,
        architecture="dense",
        context_length=32768,
        use_case=['chat', 'multilingual'],
        description="Compact multilingual Qwen 3",
        min_ram_gb=1.0,
        recommended_ram_gb=2.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=1.0, disk_gb=0.5, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=1.3, disk_gb=0.7, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=1.4, disk_gb=0.8, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=1.6, disk_gb=1.0, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=1.8, disk_gb=1.2, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=2.2, disk_gb=1.7, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=4.0, disk_gb=3.3, quality="lossless"),
        ],
        ollama_id="qwen3:1.7b",
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen3.5-2b",
        name="Qwen 3.5 2B",
        provider="Alibaba",
        family="Qwen",
        params="2B",
        params_billions=2,
        architecture="dense",
        context_length=32768,
        use_case=['chat', 'multilingual'],
        description="Small multimodal Qwen 3.5",
        min_ram_gb=1.1,
        recommended_ram_gb=2.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=1.1, disk_gb=0.6, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=1.4, disk_gb=0.9, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=1.5, disk_gb=1.2, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=1.8, disk_gb=1.2, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=2.0, disk_gb=1.4, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=2.5, disk_gb=1.9, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=4.6, disk_gb=3.9, quality="lossless"),
        ],
        ollama_id="qwen3.5:2b",
        license="Apache 2.0",
    ),
    AIModel(
        id="gemma2-2b",
        name="Gemma 2 2B",
        provider="Google",
        family="Gemma",
        params="2B",
        params_billions=2,
        architecture="dense",
        context_length=8192,
        use_case=['chat', 'edge'],
        description="Google's compact open model",
        min_ram_gb=1.1,
        recommended_ram_gb=2.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=1.1, disk_gb=0.6, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=1.4, disk_gb=0.9, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=1.5, disk_gb=1.0, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=1.8, disk_gb=1.2, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=2.0, disk_gb=1.5, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=2.5, disk_gb=2.0, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=4.6, disk_gb=3.9, quality="lossless"),
        ],
        ollama_id="gemma2:2b",
        license="Gemma",
    ),
    AIModel(
        id="llama3.2-3b",
        name="Llama 3.2 3B",
        provider="Meta",
        family="Llama",
        params="3B",
        params_billions=3,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'code'],
        description="Lightweight Llama for mobile and edge",
        min_ram_gb=1.7,
        recommended_ram_gb=2.8,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=1.5, disk_gb=0.9, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=1.8, disk_gb=1.3, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=2.0, disk_gb=1.5, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=2.4, disk_gb=1.8, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=2.8, disk_gb=2.2, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=3.6, disk_gb=2.9, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=6.6, disk_gb=5.9, quality="lossless"),
        ],
        ollama_id="llama3.2:3b",
        license="Llama 3.2 Community",
    ),
    AIModel(
        id="smollm3-3b",
        name="SmolLM3 3B",
        provider="HuggingFace",
        family="SmolLM",
        params="3B",
        params_billions=3,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'reasoning'],
        description="Lightweight multilingual reasoning",
        min_ram_gb=1.7,
        recommended_ram_gb=2.8,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=1.5, disk_gb=0.9, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=1.8, disk_gb=1.3, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=2.0, disk_gb=1.5, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=2.4, disk_gb=1.8, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=2.8, disk_gb=2.2, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=3.6, disk_gb=2.9, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=6.6, disk_gb=5.9, quality="lossless"),
        ],
        license="Apache 2.0",
    ),
    AIModel(
        id="phi-3.5-mini",
        name="Phi-3.5 Mini",
        provider="Microsoft",
        family="Phi",
        params="3.8B",
        params_billions=3.8,
        architecture="dense",
        context_length=131072,
        use_case=['reasoning', 'code', 'chat'],
        description="Microsoft's efficient small model with long context",
        min_ram_gb=2.1,
        recommended_ram_gb=3.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=1.7, disk_gb=1.2, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=2.2, disk_gb=1.6, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=2.4, disk_gb=1.9, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=2.9, disk_gb=2.3, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=3.4, disk_gb=2.8, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=4.4, disk_gb=3.7, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=8.3, disk_gb=7.4, quality="lossless"),
        ],
        ollama_id="phi3.5",
        license="MIT",
    ),
    AIModel(
        id="phi-4-mini-reasoning",
        name="Phi-4 Mini Reasoning",
        provider="Microsoft",
        family="Phi",
        params="3.8B",
        params_billions=3.8,
        architecture="dense",
        context_length=16384,
        use_case=['reasoning'],
        description="Lightweight reasoning model",
        min_ram_gb=2.1,
        recommended_ram_gb=3.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=1.7, disk_gb=1.2, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=2.2, disk_gb=1.6, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=2.4, disk_gb=1.9, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=2.9, disk_gb=2.3, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=3.4, disk_gb=2.8, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=4.4, disk_gb=3.7, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=8.3, disk_gb=7.4, quality="lossless"),
        ],
        ollama_id="phi4-mini-reasoning",
        license="MIT",
    ),
    AIModel(
        id="qwen3-4b",
        name="Qwen 3 4B",
        provider="Alibaba",
        family="Qwen",
        params="4B",
        params_billions=4,
        architecture="dense",
        context_length=32768,
        use_case=['chat', 'code'],
        description="Compact Qwen 3 for general tasks",
        min_ram_gb=2.2,
        recommended_ram_gb=3.7,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=1.8, disk_gb=1.2, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=2.3, disk_gb=1.7, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=2.5, disk_gb=2.0, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=3.1, disk_gb=2.4, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=3.6, disk_gb=2.9, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=4.6, disk_gb=3.9, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=8.7, disk_gb=7.8, quality="lossless"),
        ],
        ollama_id="qwen3:4b",
        license="Apache 2.0",
    ),
    AIModel(
        id="gemma3-4b",
        name="Gemma 3 4B",
        provider="Google",
        family="Gemma",
        params="4B",
        params_billions=4,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'vision'],
        description="Multimodal Gemma with 128K context",
        min_ram_gb=2.2,
        recommended_ram_gb=3.7,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=1.8, disk_gb=1.2, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=2.3, disk_gb=1.7, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=2.5, disk_gb=2.0, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=3.1, disk_gb=2.4, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=3.6, disk_gb=2.9, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=4.6, disk_gb=3.9, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=8.7, disk_gb=7.8, quality="lossless"),
        ],
        ollama_id="gemma3:4b",
        license="Gemma",
    ),
    AIModel(
        id="qwen3.5-4b",
        name="Qwen 3.5 4B",
        provider="Alibaba",
        family="Qwen",
        params="4B",
        params_billions=4,
        architecture="dense",
        context_length=32768,
        use_case=['chat', 'multilingual'],
        description="Small multimodal Qwen 3.5",
        min_ram_gb=2.2,
        recommended_ram_gb=3.7,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=1.8, disk_gb=1.2, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=2.3, disk_gb=1.7, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=2.5, disk_gb=2.5, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=3.1, disk_gb=2.4, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=3.6, disk_gb=3.2, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=4.6, disk_gb=4.2, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=8.7, disk_gb=7.8, quality="lossless"),
        ],
        ollama_id="qwen3.5:4b",
        license="Apache 2.0",
    ),
    AIModel(
        id="gemma4-e2b-it",
        name="Gemma 4 E2B IT",
        provider="Google",
        family="Gemma",
        params="5B",
        params_billions=5,
        architecture="dense",
        context_length=262144,
        use_case=['chat', 'vision'],
        description="Gemma 4 efficient instruct model (official)",
        min_ram_gb=2.8,
        recommended_ram_gb=4.7,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=2.1, disk_gb=1.5, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=2.7, disk_gb=2.1, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=3.1, disk_gb=3.2, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=3.7, disk_gb=3.1, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=4.3, disk_gb=3.6, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=5.6, disk_gb=4.6, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=10.7, disk_gb=9.8, quality="lossless"),
        ],
        license="Gemma",
    ),
    AIModel(
        id="gemma4-e2b",
        name="Gemma 4 E2B",
        provider="Google",
        family="Gemma",
        params="5B",
        params_billions=5,
        architecture="dense",
        context_length=262144,
        use_case=['vision'],
        description="Gemma 4 efficient base model (official)",
        min_ram_gb=2.8,
        recommended_ram_gb=4.7,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=2.1, disk_gb=1.5, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=2.7, disk_gb=2.1, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=3.1, disk_gb=2.4, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=3.7, disk_gb=3.1, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=4.3, disk_gb=3.7, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=5.6, disk_gb=4.9, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=10.7, disk_gb=9.8, quality="lossless"),
        ],
        license="Gemma",
    ),
    AIModel(
        id="gemma4-e4b-it",
        name="Gemma 4 E4B IT",
        provider="Google",
        family="Gemma",
        params="8B",
        params_billions=8,
        architecture="dense",
        context_length=262144,
        use_case=['chat', 'vision'],
        description="Gemma 4 balanced instruct model (official)",
        min_ram_gb=4.5,
        recommended_ram_gb=7.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=3.1, disk_gb=2.4, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=4.1, disk_gb=3.4, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=4.6, disk_gb=5, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=5.6, disk_gb=4.9, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=6.6, disk_gb=5.8, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=8.7, disk_gb=7.5, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=16.9, disk_gb=15.6, quality="lossless"),
        ],
        license="Gemma",
    ),
    AIModel(
        id="gemma4-e4b",
        name="Gemma 4 E4B",
        provider="Google",
        family="Gemma",
        params="8B",
        params_billions=8,
        architecture="dense",
        context_length=262144,
        use_case=['vision'],
        description="Gemma 4 balanced base model (official)",
        min_ram_gb=4.5,
        recommended_ram_gb=7.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=3.1, disk_gb=2.4, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=4.1, disk_gb=3.4, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=4.6, disk_gb=3.9, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=5.6, disk_gb=4.9, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=6.6, disk_gb=5.9, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=8.7, disk_gb=7.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=16.9, disk_gb=15.6, quality="lossless"),
        ],
        license="Gemma",
    ),
    AIModel(
        id="mistral-7b",
        name="Mistral 7B v0.3",
        provider="Mistral AI",
        family="Mistral",
        params="7B",
        params_billions=7,
        architecture="dense",
        context_length=32768,
        use_case=['chat', 'reasoning'],
        description="High-quality 7B with sliding window attention",
        min_ram_gb=3.9,
        recommended_ram_gb=6.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=2.7, disk_gb=2.1, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=3.6, disk_gb=3.0, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=4.1, disk_gb=3.4, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=5.0, disk_gb=4.3, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=5.9, disk_gb=5.1, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=7.7, disk_gb=6.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=14.8, disk_gb=13.7, quality="lossless"),
        ],
        ollama_id="mistral",
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen2.5-7b",
        name="Qwen 2.5 7B",
        provider="Alibaba",
        family="Qwen",
        params="7B",
        params_billions=7,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'multilingual', 'code'],
        description="Strong multilingual and coding capabilities",
        min_ram_gb=3.9,
        recommended_ram_gb=6.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=2.7, disk_gb=2.1, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=3.6, disk_gb=3.0, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=4.1, disk_gb=3.4, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=5.0, disk_gb=4.3, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=5.9, disk_gb=5.1, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=7.7, disk_gb=6.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=14.8, disk_gb=13.7, quality="lossless"),
        ],
        ollama_id="qwen2.5:7b",
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen2.5-coder-7b",
        name="Qwen 2.5 Coder 7B",
        provider="Alibaba",
        family="Qwen",
        params="7B",
        params_billions=7,
        architecture="dense",
        context_length=131072,
        use_case=['code'],
        description="Dedicated coding model",
        min_ram_gb=3.9,
        recommended_ram_gb=6.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=2.7, disk_gb=2.1, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=3.6, disk_gb=3.0, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=4.1, disk_gb=3.4, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=5.0, disk_gb=4.3, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=5.9, disk_gb=5.1, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=7.7, disk_gb=6.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=14.8, disk_gb=13.7, quality="lossless"),
        ],
        ollama_id="qwen2.5-coder:7b",
        license="Apache 2.0",
    ),
    AIModel(
        id="deepseek-r1-7b",
        name="DeepSeek R1 Distill 7B",
        provider="DeepSeek",
        family="DeepSeek",
        params="7B",
        params_billions=7,
        architecture="dense",
        context_length=65536,
        use_case=['reasoning'],
        description="R1 reasoning distilled into Qwen 7B",
        min_ram_gb=3.9,
        recommended_ram_gb=6.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=2.7, disk_gb=2.1, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=3.6, disk_gb=3.0, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=4.1, disk_gb=3.4, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=5.0, disk_gb=4.3, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=5.9, disk_gb=5.1, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=7.7, disk_gb=6.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=14.8, disk_gb=13.7, quality="lossless"),
        ],
        ollama_id="deepseek-r1:7b",
        license="MIT",
    ),
    AIModel(
        id="llama3.1-8b",
        name="Llama 3.1 8B",
        provider="Meta",
        family="Llama",
        params="8B",
        params_billions=8,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'code', 'reasoning'],
        description="Meta's versatile 8B — great quality/speed ratio",
        min_ram_gb=4.5,
        recommended_ram_gb=7.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=3.1, disk_gb=2.4, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=4.1, disk_gb=3.4, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=4.6, disk_gb=3.9, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=5.6, disk_gb=4.9, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=6.6, disk_gb=5.9, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=8.7, disk_gb=7.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=16.9, disk_gb=15.6, quality="lossless"),
        ],
        ollama_id="llama3.1:8b",
        featured=True,
        license="Llama 3.1 Community",
    ),
    AIModel(
        id="qwen3-8b",
        name="Qwen 3 8B",
        provider="Alibaba",
        family="Qwen",
        params="8B",
        params_billions=8,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'code', 'reasoning'],
        description="Qwen 3 with thinking mode support",
        min_ram_gb=4.5,
        recommended_ram_gb=7.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=3.1, disk_gb=2.4, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=4.1, disk_gb=3.4, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=4.6, disk_gb=3.9, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=5.6, disk_gb=4.9, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=6.6, disk_gb=5.9, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=8.7, disk_gb=7.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=16.9, disk_gb=15.6, quality="lossless"),
        ],
        ollama_id="qwen3:8b",
        license="Apache 2.0",
    ),
    AIModel(
        id="ministral-8b",
        name="Ministral 8B",
        provider="Mistral AI",
        family="Mistral",
        params="8B",
        params_billions=8,
        architecture="dense",
        context_length=32768,
        use_case=['chat'],
        description="Mistral's efficient 8B model",
        min_ram_gb=4.5,
        recommended_ram_gb=7.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=3.1, disk_gb=2.4, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=4.1, disk_gb=3.4, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=4.6, disk_gb=3.9, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=5.6, disk_gb=4.9, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=6.6, disk_gb=5.9, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=8.7, disk_gb=7.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=16.9, disk_gb=15.6, quality="lossless"),
        ],
        ollama_id="ministral-3:8b",
        license="MRL",
    ),
    AIModel(
        id="gemma2-9b",
        name="Gemma 2 9B",
        provider="Google",
        family="Gemma",
        params="9B",
        params_billions=9,
        architecture="dense",
        context_length=8192,
        use_case=['chat', 'reasoning'],
        description="Google's best mid-size open model",
        min_ram_gb=5.0,
        recommended_ram_gb=8.4,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=3.4, disk_gb=2.8, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=4.5, disk_gb=3.9, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=5.1, disk_gb=4.4, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=6.3, disk_gb=5.5, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=7.4, disk_gb=6.6, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=9.7, disk_gb=8.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=18.9, disk_gb=17.6, quality="lossless"),
        ],
        ollama_id="gemma2:9b",
        license="Gemma",
    ),
    AIModel(
        id="glm-4-9b",
        name="GLM-4 9B",
        provider="Zhipu AI",
        family="GLM",
        params="9B",
        params_billions=9,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'multilingual', 'code'],
        description="Multilingual model supporting 26 languages with 128K context",
        min_ram_gb=5.0,
        recommended_ram_gb=8.4,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=3.4, disk_gb=2.8, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=4.5, disk_gb=3.9, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=5.1, disk_gb=4.4, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=6.3, disk_gb=5.5, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=7.4, disk_gb=6.6, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=9.7, disk_gb=8.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=18.9, disk_gb=17.6, quality="lossless"),
        ],
        ollama_id="glm4:9b",
        license="GLM-4",
    ),
    AIModel(
        id="nemotron-nano-9b",
        name="Nemotron Nano 9B v2",
        provider="NVIDIA",
        family="Nemotron",
        params="9B",
        params_billions=9,
        architecture="dense",
        context_length=131072,
        use_case=['reasoning'],
        description="Hybrid Mamba2 architecture for reasoning",
        min_ram_gb=5.0,
        recommended_ram_gb=8.4,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=3.4, disk_gb=2.8, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=4.5, disk_gb=3.9, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=5.1, disk_gb=4.4, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=6.3, disk_gb=5.5, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=7.4, disk_gb=6.6, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=9.7, disk_gb=8.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=18.9, disk_gb=17.6, quality="lossless"),
        ],
        license="NVIDIA Open",
    ),
    AIModel(
        id="qwen3.5-9b",
        name="Qwen 3.5 9B",
        provider="Alibaba",
        family="Qwen",
        params="9B",
        params_billions=9,
        architecture="dense",
        context_length=32768,
        use_case=['chat', 'vision'],
        description="Multimodal Qwen 3.5 mid-size",
        min_ram_gb=5.0,
        recommended_ram_gb=8.4,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=3.4, disk_gb=2.8, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=4.5, disk_gb=3.9, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=5.1, disk_gb=5.2, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=6.3, disk_gb=5.5, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=7.4, disk_gb=6.9, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=9.7, disk_gb=8.9, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=18.9, disk_gb=17.6, quality="lossless"),
        ],
        ollama_id="qwen3.5:9b",
        featured=True,
        license="Apache 2.0",
    ),
    AIModel(
        id="llama3.2-11b-vision",
        name="Llama 3.2 11B Vision",
        provider="Meta",
        family="Llama",
        params="11B",
        params_billions=11,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'vision'],
        description="Multimodal vision and text model",
        min_ram_gb=6.1,
        recommended_ram_gb=10.2,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=4.0, disk_gb=3.4, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=5.4, disk_gb=4.7, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=6.1, disk_gb=5.4, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=7.5, disk_gb=6.7, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=9.0, disk_gb=8.1, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=11.8, disk_gb=10.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=23.0, disk_gb=21.5, quality="lossless"),
        ],
        ollama_id="llama3.2-vision:11b",
        license="Llama 3.2 Community",
    ),
    AIModel(
        id="gemma3-12b",
        name="Gemma 3 12B",
        provider="Google",
        family="Gemma",
        params="12B",
        params_billions=12,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'vision', 'reasoning'],
        description="Multimodal Gemma with 128K context",
        min_ram_gb=6.7,
        recommended_ram_gb=11.2,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=4.3, disk_gb=3.7, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=5.9, disk_gb=5.1, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=6.6, disk_gb=5.9, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=8.2, disk_gb=7.3, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=9.7, disk_gb=8.8, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=12.8, disk_gb=11.7, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=25.1, disk_gb=23.5, quality="lossless"),
        ],
        ollama_id="gemma3:12b",
        license="Gemma",
    ),
    AIModel(
        id="mistral-nemo-12b",
        name="Mistral Nemo 12B",
        provider="Mistral AI",
        family="Mistral",
        params="12B",
        params_billions=12,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'multilingual'],
        description="Multilingual 12B with 128K context",
        min_ram_gb=6.7,
        recommended_ram_gb=11.2,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=4.3, disk_gb=3.7, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=5.9, disk_gb=5.1, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=6.6, disk_gb=5.9, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=8.2, disk_gb=7.3, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=9.7, disk_gb=8.8, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=12.8, disk_gb=11.7, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=25.1, disk_gb=23.5, quality="lossless"),
        ],
        ollama_id="mistral-nemo",
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen2.5-14b",
        name="Qwen 2.5 14B",
        provider="Alibaba",
        family="Qwen",
        params="14B",
        params_billions=14,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'multilingual', 'reasoning'],
        description="Excellent quality for its size class",
        min_ram_gb=7.8,
        recommended_ram_gb=13.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=5.0, disk_gb=4.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=6.8, disk_gb=6.0, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=7.7, disk_gb=6.8, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=9.5, disk_gb=8.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=11.3, disk_gb=10.3, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=14.8, disk_gb=13.7, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=29.2, disk_gb=27.4, quality="lossless"),
        ],
        ollama_id="qwen2.5:14b",
        license="Apache 2.0",
    ),
    AIModel(
        id="phi-4-14b",
        name="Phi-4 14B",
        provider="Microsoft",
        family="Phi",
        params="14B",
        params_billions=14,
        architecture="dense",
        context_length=16384,
        use_case=['reasoning', 'code'],
        description="Microsoft's reasoning-focused model",
        min_ram_gb=7.8,
        recommended_ram_gb=13.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=5.0, disk_gb=4.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=6.8, disk_gb=6.0, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=7.7, disk_gb=6.8, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=9.5, disk_gb=8.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=11.3, disk_gb=10.3, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=14.8, disk_gb=13.7, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=29.2, disk_gb=27.4, quality="lossless"),
        ],
        ollama_id="phi4",
        featured=True,
        license="MIT",
    ),
    AIModel(
        id="qwen3-14b",
        name="Qwen 3 14B",
        provider="Alibaba",
        family="Qwen",
        params="14B",
        params_billions=14,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'code', 'reasoning'],
        description="Strong all-rounder with thinking mode",
        min_ram_gb=7.8,
        recommended_ram_gb=13.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=5.0, disk_gb=4.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=6.8, disk_gb=6.0, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=7.7, disk_gb=6.8, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=9.5, disk_gb=8.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=11.3, disk_gb=10.3, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=14.8, disk_gb=13.7, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=29.2, disk_gb=27.4, quality="lossless"),
        ],
        ollama_id="qwen3:14b",
        license="Apache 2.0",
    ),
    AIModel(
        id="deepseek-r1-14b",
        name="DeepSeek R1 Distill 14B",
        provider="DeepSeek",
        family="DeepSeek",
        params="14B",
        params_billions=14,
        architecture="dense",
        context_length=65536,
        use_case=['reasoning'],
        description="R1 reasoning distilled into Qwen 14B",
        min_ram_gb=7.8,
        recommended_ram_gb=13.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=5.0, disk_gb=4.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=6.8, disk_gb=6.0, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=7.7, disk_gb=6.8, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=9.5, disk_gb=8.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=11.3, disk_gb=10.3, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=14.8, disk_gb=13.7, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=29.2, disk_gb=27.4, quality="lossless"),
        ],
        ollama_id="deepseek-r1:14b",
        license="MIT",
    ),
    AIModel(
        id="llama4-scout-17b",
        name="Llama 4 Scout 17B",
        provider="Meta",
        family="Llama",
        params="109B",
        params_billions=109,
        architecture="moe",
        context_length=131072,
        use_case=['chat', 'vision', 'reasoning'],
        description="MoE with 16 experts, 17B active params",
        min_ram_gb=60.9,
        recommended_ram_gb=101.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=35.4, disk_gb=33.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=49.4, disk_gb=46.6, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=56.3, disk_gb=53.3, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=70.3, disk_gb=66.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=84.2, disk_gb=79.9, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=112.2, disk_gb=106.6, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=223.8, disk_gb=213.2, quality="lossless"),
        ],
        active_params="17B active",
        moe_info={'numExperts': 16, 'activeExperts': 1, 'activeParameters': 17000000000},
        ollama_id="llama4:scout",
        featured=True,
        license="Llama 4 Community",
    ),
    AIModel(
        id="gpt-oss-20b",
        name="GPT-OSS 20B",
        provider="OpenAI",
        family="GPT-OSS",
        params="21B",
        params_billions=21,
        architecture="moe",
        context_length=131072,
        use_case=['chat', 'reasoning', 'code'],
        description="OpenAI's open-weight MoE with configurable reasoning",
        min_ram_gb=11.7,
        recommended_ram_gb=19.6,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=7.2, disk_gb=6.4, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=9.9, disk_gb=9.0, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=11.3, disk_gb=10.3, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=13.9, disk_gb=12.8, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=16.6, disk_gb=15.4, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=22.0, disk_gb=20.5, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=43.5, disk_gb=41.1, quality="lossless"),
        ],
        active_params="3.6B active",
        moe_info={'numExperts': 16, 'activeExperts': 2, 'activeParameters': 3600000000},
        ollama_id="gpt-oss:20b",
        featured=True,
        license="Apache 2.0",
    ),
    AIModel(
        id="lfm2-24b",
        name="LFM2 24B",
        provider="Liquid AI",
        family="LFM",
        params="24B",
        params_billions=24,
        architecture="moe",
        context_length=32768,
        use_case=['chat', 'edge', 'rag'],
        description="Hybrid MoE with convolution+attention layers — 2.3B active",
        min_ram_gb=13.4,
        recommended_ram_gb=22.4,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=8.2, disk_gb=7.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=11.3, disk_gb=10.3, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=12.8, disk_gb=11.7, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=15.9, disk_gb=14.7, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=18.9, disk_gb=17.6, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=25.1, disk_gb=23.5, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=49.7, disk_gb=46.9, quality="lossless"),
        ],
        active_params="2.3B active",
        moe_info={'numExperts': 64, 'activeExperts': 4, 'activeParameters': 2300000000},
        ollama_id="lfm2:24b",
        license="Liquid AI",
    ),
    AIModel(
        id="devstral-small-2-24b",
        name="Devstral Small 2 24B",
        provider="Mistral AI",
        family="Mistral",
        params="24B",
        params_billions=24,
        architecture="dense",
        context_length=262144,
        use_case=['code'],
        description="Coding-focused model with 256K context — 68% SWE-bench",
        min_ram_gb=13.4,
        recommended_ram_gb=22.4,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=8.2, disk_gb=7.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=11.3, disk_gb=10.3, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=12.8, disk_gb=11.7, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=15.9, disk_gb=14.7, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=18.9, disk_gb=17.6, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=25.1, disk_gb=23.5, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=49.7, disk_gb=46.9, quality="lossless"),
        ],
        ollama_id="devstral-small-2",
        license="Apache 2.0",
    ),
    AIModel(
        id="mistral-small-24b",
        name="Mistral Small 3.1 24B",
        provider="Mistral AI",
        family="Mistral",
        params="24B",
        params_billions=24,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'vision', 'code'],
        description="Multimodal Mistral with vision support",
        min_ram_gb=13.4,
        recommended_ram_gb=22.4,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=8.2, disk_gb=7.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=11.3, disk_gb=10.3, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=12.8, disk_gb=11.7, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=15.9, disk_gb=14.7, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=18.9, disk_gb=17.6, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=25.1, disk_gb=23.5, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=49.7, disk_gb=46.9, quality="lossless"),
        ],
        ollama_id="mistral-small",
        featured=True,
        license="Apache 2.0",
    ),
    AIModel(
        id="gemma2-27b",
        name="Gemma 2 27B",
        provider="Google",
        family="Gemma",
        params="27B",
        params_billions=27,
        architecture="dense",
        context_length=8192,
        use_case=['chat', 'reasoning'],
        description="Google's largest Gemma 2 model",
        min_ram_gb=15.1,
        recommended_ram_gb=25.1,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=9.1, disk_gb=8.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=12.6, disk_gb=11.6, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=14.3, disk_gb=13.2, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=17.8, disk_gb=16.5, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=21.2, disk_gb=19.8, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=28.2, disk_gb=26.4, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=55.8, disk_gb=52.8, quality="lossless"),
        ],
        ollama_id="gemma2:27b",
        license="Gemma",
    ),
    AIModel(
        id="gemma3-27b",
        name="Gemma 3 27B",
        provider="Google",
        family="Gemma",
        params="27B",
        params_billions=27,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'vision', 'reasoning'],
        description="Google's flagship Gemma 3 model",
        min_ram_gb=15.1,
        recommended_ram_gb=25.1,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=9.1, disk_gb=8.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=12.6, disk_gb=11.6, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=14.3, disk_gb=13.2, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=17.8, disk_gb=16.5, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=21.2, disk_gb=19.8, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=28.2, disk_gb=26.4, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=55.8, disk_gb=52.8, quality="lossless"),
        ],
        ollama_id="gemma3:27b",
        featured=True,
        license="Gemma",
    ),
    AIModel(
        id="gemma4-26b-a4b-it",
        name="Gemma 4 26B-A4B IT",
        provider="Google",
        family="Gemma",
        params="27B",
        params_billions=27,
        architecture="moe",
        context_length=262144,
        use_case=['chat', 'vision', 'reasoning'],
        description="Gemma 4 MoE instruct model (official)",
        min_ram_gb=15.1,
        recommended_ram_gb=25.1,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=9.1, disk_gb=8.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=12.6, disk_gb=11.6, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=14.3, disk_gb=15.6, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=17.8, disk_gb=16.5, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=21.2, disk_gb=21.1, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=28.2, disk_gb=25, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=55.8, disk_gb=52.8, quality="lossless"),
        ],
        active_params="4B active",
        moe_info={'numExperts': 26, 'activeExperts': 4, 'activeParameters': 4000000000},
        license="Gemma",
    ),
    AIModel(
        id="gemma4-26b-a4b",
        name="Gemma 4 26B-A4B",
        provider="Google",
        family="Gemma",
        params="27B",
        params_billions=27,
        architecture="moe",
        context_length=262144,
        use_case=['vision', 'reasoning'],
        description="Gemma 4 MoE base model (official)",
        min_ram_gb=15.1,
        recommended_ram_gb=25.1,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=9.1, disk_gb=8.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=12.6, disk_gb=11.6, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=14.3, disk_gb=13.2, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=17.8, disk_gb=16.5, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=21.2, disk_gb=19.8, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=28.2, disk_gb=26.4, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=55.8, disk_gb=52.8, quality="lossless"),
        ],
        active_params="4B active",
        moe_info={'numExperts': 26, 'activeExperts': 4, 'activeParameters': 4000000000},
        license="Gemma",
    ),
    AIModel(
        id="qwen3.5-27b",
        name="Qwen 3.5 27B",
        provider="Alibaba",
        family="Qwen",
        params="27.8B",
        params_billions=27.8,
        architecture="dense",
        context_length=262144,
        use_case=['chat', 'vision', 'reasoning'],
        description="Flagship native multimodal Qwen 3.5",
        min_ram_gb=15.5,
        recommended_ram_gb=25.9,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=9.4, disk_gb=8.5, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=13.0, disk_gb=11.9, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=14.7, disk_gb=15.4, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=18.3, disk_gb=17.0, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=21.9, disk_gb=20.6, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=29.0, disk_gb=26.6, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=57.5, disk_gb=54.4, quality="lossless"),
        ],
        ollama_id="qwen3.5:27b",
        license="Apache 2.0",
    ),
    AIModel(
        id="gemma4-31b-it",
        name="Gemma 4 31B IT",
        provider="Google",
        family="Gemma",
        params="33B",
        params_billions=33,
        architecture="dense",
        context_length=262144,
        use_case=['chat', 'vision', 'reasoning'],
        description="Gemma 4 flagship instruct model (official)",
        min_ram_gb=18.4,
        recommended_ram_gb=30.7,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=11.1, disk_gb=10.1, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=15.3, disk_gb=14.1, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=17.4, disk_gb=17.4, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=21.6, disk_gb=20.2, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=25.9, disk_gb=23.5, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=34.3, disk_gb=30.4, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=68.1, disk_gb=64.5, quality="lossless"),
        ],
        license="Gemma",
    ),
    AIModel(
        id="gemma4-31b",
        name="Gemma 4 31B",
        provider="Google",
        family="Gemma",
        params="33B",
        params_billions=33,
        architecture="dense",
        context_length=262144,
        use_case=['vision', 'reasoning'],
        description="Gemma 4 flagship base model (official)",
        min_ram_gb=18.4,
        recommended_ram_gb=30.7,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=11.1, disk_gb=10.1, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=15.3, disk_gb=14.1, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=17.4, disk_gb=16.1, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=21.6, disk_gb=20.2, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=25.9, disk_gb=24.2, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=34.3, disk_gb=32.3, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=68.1, disk_gb=64.5, quality="lossless"),
        ],
        license="Gemma",
    ),
    AIModel(
        id="qwen3-30b-a3b",
        name="Qwen 3 30B-A3B",
        provider="Alibaba",
        family="Qwen",
        params="30B",
        params_billions=30,
        architecture="moe",
        context_length=131072,
        use_case=['chat', 'reasoning'],
        description="MoE with only 3.3B active — extremely efficient",
        min_ram_gb=16.8,
        recommended_ram_gb=27.9,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=10.1, disk_gb=9.2, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=13.9, disk_gb=12.8, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=15.9, disk_gb=14.7, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=19.7, disk_gb=18.3, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=23.6, disk_gb=22.0, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=31.2, disk_gb=29.3, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=62.0, disk_gb=58.7, quality="lossless"),
        ],
        active_params="3.3B active",
        moe_info={'numExperts': 128, 'activeExperts': 8, 'activeParameters': 3300000000},
        ollama_id="qwen3:30b-a3b",
        license="Apache 2.0",
    ),
    AIModel(
        id="nemotron-nano-30b",
        name="Nemotron 3 Nano 30B",
        provider="NVIDIA",
        family="Nemotron",
        params="30B",
        params_billions=30,
        architecture="moe",
        context_length=1048576,
        use_case=['chat', 'reasoning'],
        description="MoE with 1M context and 3B active",
        min_ram_gb=16.8,
        recommended_ram_gb=27.9,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=10.1, disk_gb=9.2, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=13.9, disk_gb=12.8, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=15.9, disk_gb=14.7, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=19.7, disk_gb=18.3, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=23.6, disk_gb=22.0, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=31.2, disk_gb=29.3, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=62.0, disk_gb=58.7, quality="lossless"),
        ],
        active_params="3B active",
        moe_info={'numExperts': 128, 'activeExperts': 6, 'activeParameters': 3000000000},
        ollama_id="nemotron-3-nano:30b",
        license="NVIDIA Open",
    ),
    AIModel(
        id="qwen2.5-32b",
        name="Qwen 2.5 32B",
        provider="Alibaba",
        family="Qwen",
        params="32B",
        params_billions=32,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'multilingual', 'reasoning'],
        description="High-quality reasoning and multilingual",
        min_ram_gb=17.9,
        recommended_ram_gb=29.8,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=10.7, disk_gb=9.8, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=14.8, disk_gb=13.7, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=16.9, disk_gb=15.6, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=21.0, disk_gb=19.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=25.1, disk_gb=23.5, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=33.3, disk_gb=31.3, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=66.1, disk_gb=62.6, quality="lossless"),
        ],
        ollama_id="qwen2.5:32b",
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen2.5-coder-32b",
        name="Qwen 2.5 Coder 32B",
        provider="Alibaba",
        family="Qwen",
        params="32B",
        params_billions=32,
        architecture="dense",
        context_length=131072,
        use_case=['code'],
        description="Best open-source coding model at release",
        min_ram_gb=17.9,
        recommended_ram_gb=29.8,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=10.7, disk_gb=9.8, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=14.8, disk_gb=13.7, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=16.9, disk_gb=15.6, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=21.0, disk_gb=19.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=25.1, disk_gb=23.5, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=33.3, disk_gb=31.3, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=66.1, disk_gb=62.6, quality="lossless"),
        ],
        ollama_id="qwen2.5-coder:32b",
        featured=True,
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen3-32b",
        name="Qwen 3 32B",
        provider="Alibaba",
        family="Qwen",
        params="32B",
        params_billions=32,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'code', 'reasoning'],
        description="Qwen 3 flagship dense model",
        min_ram_gb=17.9,
        recommended_ram_gb=29.8,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=10.7, disk_gb=9.8, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=14.8, disk_gb=13.7, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=16.9, disk_gb=15.6, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=21.0, disk_gb=19.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=25.1, disk_gb=23.5, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=33.3, disk_gb=31.3, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=66.1, disk_gb=62.6, quality="lossless"),
        ],
        ollama_id="qwen3:32b",
        featured=True,
        license="Apache 2.0",
    ),
    AIModel(
        id="deepseek-r1-32b",
        name="DeepSeek R1 Distill 32B",
        provider="DeepSeek",
        family="DeepSeek",
        params="32B",
        params_billions=32,
        architecture="dense",
        context_length=65536,
        use_case=['reasoning'],
        description="R1 reasoning distilled into Qwen 32B — sweet spot",
        min_ram_gb=17.9,
        recommended_ram_gb=29.8,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=10.7, disk_gb=9.8, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=14.8, disk_gb=13.7, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=16.9, disk_gb=15.6, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=21.0, disk_gb=19.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=25.1, disk_gb=23.5, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=33.3, disk_gb=31.3, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=66.1, disk_gb=62.6, quality="lossless"),
        ],
        ollama_id="deepseek-r1:32b",
        featured=True,
        license="MIT",
    ),
    AIModel(
        id="exaone-4-32b",
        name="EXAONE 4.0 32B",
        provider="LG AI",
        family="EXAONE",
        params="32B",
        params_billions=32,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'reasoning'],
        description="Hybrid reasoning, multilingual",
        min_ram_gb=17.9,
        recommended_ram_gb=29.8,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=10.7, disk_gb=9.8, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=14.8, disk_gb=13.7, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=16.9, disk_gb=15.6, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=21.0, disk_gb=19.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=25.1, disk_gb=23.5, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=33.3, disk_gb=31.3, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=66.1, disk_gb=62.6, quality="lossless"),
        ],
        license="EXAONE AI",
    ),
    AIModel(
        id="olmo2-32b",
        name="OLMo 2 32B",
        provider="Allen AI",
        family="OLMo",
        params="32B",
        params_billions=32,
        architecture="dense",
        context_length=4096,
        use_case=['chat', 'reasoning'],
        description="Fully open research model by Allen AI",
        min_ram_gb=17.9,
        recommended_ram_gb=29.8,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=10.7, disk_gb=9.8, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=14.8, disk_gb=13.7, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=16.9, disk_gb=15.6, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=21.0, disk_gb=19.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=25.1, disk_gb=23.5, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=33.3, disk_gb=31.3, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=66.1, disk_gb=62.6, quality="lossless"),
        ],
        license="Apache 2.0",
    ),
    AIModel(
        id="command-r-35b",
        name="Command R 35B",
        provider="Cohere",
        family="Command",
        params="35B",
        params_billions=35,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'rag'],
        description="Optimized for retrieval-augmented generation",
        min_ram_gb=19.6,
        recommended_ram_gb=32.6,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=11.7, disk_gb=10.7, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=16.2, disk_gb=15.0, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=18.4, disk_gb=17.1, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=22.9, disk_gb=21.4, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=27.4, disk_gb=25.7, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=36.4, disk_gb=34.2, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=72.2, disk_gb=68.5, quality="lossless"),
        ],
        ollama_id="command-r:35b",
        license="CC BY-NC 4.0",
    ),
    AIModel(
        id="qwen3.5-35b-a3b",
        name="Qwen 3.5 35B-A3B",
        provider="Alibaba",
        family="Qwen",
        params="35B",
        params_billions=35,
        architecture="moe",
        context_length=262144,
        use_case=['chat', 'vision'],
        description="Efficient multimodal MoE with 3B active",
        min_ram_gb=19.6,
        recommended_ram_gb=32.6,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=11.7, disk_gb=10.7, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=16.2, disk_gb=15.0, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=18.4, disk_gb=19.7, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=22.9, disk_gb=21.4, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=27.4, disk_gb=26.6, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=36.4, disk_gb=34.4, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=72.2, disk_gb=68.5, quality="lossless"),
        ],
        active_params="3B active",
        moe_info={'numExperts': 256, 'activeExperts': 8, 'activeParameters': 3000000000},
        ollama_id="qwen3.5:35b-a3b",
        license="Apache 2.0",
    ),
    AIModel(
        id="mixtral-8x7b",
        name="Mixtral 8x7B",
        provider="Mistral AI",
        family="Mistral",
        params="47B",
        params_billions=47,
        architecture="moe",
        context_length=32768,
        use_case=['chat', 'code'],
        description="MoE with 12.9B active params",
        min_ram_gb=26.3,
        recommended_ram_gb=43.8,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=15.5, disk_gb=14.4, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=21.6, disk_gb=20.1, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=24.6, disk_gb=23.0, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=30.6, disk_gb=28.7, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=36.6, disk_gb=34.5, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=48.6, disk_gb=46.0, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=96.8, disk_gb=91.9, quality="lossless"),
        ],
        active_params="12.9B active",
        moe_info={'numExperts': 8, 'activeExperts': 2, 'activeParameters': 12900000000},
        ollama_id="mixtral:8x7b",
        license="Apache 2.0",
    ),
    AIModel(
        id="llama3.3-70b",
        name="Llama 3.3 70B",
        provider="Meta",
        family="Llama",
        params="70B",
        params_billions=70,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'reasoning', 'code'],
        description="Best open model at 70B class",
        min_ram_gb=39.1,
        recommended_ram_gb=65.2,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=22.9, disk_gb=21.4, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=31.9, disk_gb=29.9, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=36.4, disk_gb=34.2, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=45.3, disk_gb=42.8, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=54.3, disk_gb=51.3, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=72.2, disk_gb=68.5, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=143.9, disk_gb=136.9, quality="lossless"),
        ],
        ollama_id="llama3.3:70b",
        featured=True,
        license="Llama 3.3 Community",
    ),
    AIModel(
        id="gpt-oss-120b",
        name="GPT-OSS 120B",
        provider="OpenAI",
        family="GPT-OSS",
        params="117B",
        params_billions=117,
        architecture="moe",
        context_length=131072,
        use_case=['chat', 'reasoning', 'code'],
        description="OpenAI's flagship open-weight MoE — 52.6% SWE-bench",
        min_ram_gb=65.4,
        recommended_ram_gb=109.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=38.0, disk_gb=35.8, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=52.9, disk_gb=50.1, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=60.4, disk_gb=57.2, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=75.4, disk_gb=71.5, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=90.4, disk_gb=85.8, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=120.4, disk_gb=114.4, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=240.2, disk_gb=228.8, quality="lossless"),
        ],
        active_params="5.1B active",
        moe_info={'numExperts': 16, 'activeExperts': 2, 'activeParameters': 5100000000},
        ollama_id="gpt-oss:120b",
        featured=True,
        license="Apache 2.0",
    ),
    AIModel(
        id="devstral-2-123b",
        name="Devstral 2 123B",
        provider="Mistral AI",
        family="Mistral",
        params="123B",
        params_billions=123,
        architecture="dense",
        context_length=262144,
        use_case=['code'],
        description="Dense 123B coding model — 72.2% SWE-bench Verified",
        min_ram_gb=68.7,
        recommended_ram_gb=114.6,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=39.9, disk_gb=37.6, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=55.6, disk_gb=52.6, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=63.5, disk_gb=60.1, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=79.3, disk_gb=75.2, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=95.0, disk_gb=90.2, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=126.5, disk_gb=120.3, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=252.5, disk_gb=240.6, quality="lossless"),
        ],
        ollama_id="devstral-2",
        featured=True,
        license="MRL",
    ),
    AIModel(
        id="qwen2.5-72b",
        name="Qwen 2.5 72B",
        provider="Alibaba",
        family="Qwen",
        params="72B",
        params_billions=72,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'multilingual', 'reasoning', 'code'],
        description="Alibaba's flagship open model",
        min_ram_gb=40.2,
        recommended_ram_gb=67.1,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=23.6, disk_gb=22.0, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=32.8, disk_gb=30.8, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=37.4, disk_gb=35.2, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=46.6, disk_gb=44.0, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=55.8, disk_gb=52.8, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=74.3, disk_gb=70.4, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=148.0, disk_gb=140.8, quality="lossless"),
        ],
        ollama_id="qwen2.5:72b",
        license="Qwen",
    ),
    AIModel(
        id="qwen3.5-122b-a10b",
        name="Qwen 3.5 122B-A10B",
        provider="Alibaba",
        family="Qwen",
        params="122B",
        params_billions=122,
        architecture="moe",
        context_length=262144,
        use_case=['chat', 'vision', 'reasoning'],
        description="Large multimodal MoE",
        min_ram_gb=68.2,
        recommended_ram_gb=113.6,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=39.6, disk_gb=37.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=55.2, disk_gb=52.2, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=63.0, disk_gb=37.3, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=78.6, disk_gb=74.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=94.2, disk_gb=37.1, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=125.5, disk_gb=37.2, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=250.5, disk_gb=238.6, quality="lossless"),
        ],
        active_params="10B active",
        moe_info={'numExperts': 256, 'activeExperts': 8, 'activeParameters': 10000000000},
        ollama_id="qwen3.5:122b-a10b",
        license="Apache 2.0",
    ),
    AIModel(
        id="mixtral-8x22b",
        name="Mixtral 8x22B",
        provider="Mistral AI",
        family="Mistral",
        params="141B",
        params_billions=141,
        architecture="moe",
        context_length=65536,
        use_case=['chat', 'code', 'reasoning'],
        description="Large MoE with 39B active params",
        min_ram_gb=78.8,
        recommended_ram_gb=131.3,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=45.6, disk_gb=43.1, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=63.7, disk_gb=60.3, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=72.7, disk_gb=68.9, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=90.8, disk_gb=86.2, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=108.8, disk_gb=103.4, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=144.9, disk_gb=137.9, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=289.4, disk_gb=275.8, quality="lossless"),
        ],
        active_params="39B active",
        moe_info={'numExperts': 8, 'activeExperts': 2, 'activeParameters': 39100000000},
        ollama_id="mixtral:8x22b",
        license="Apache 2.0",
    ),
    AIModel(
        id="llama4-maverick-17b-128e",
        name="Llama 4 Maverick 17B-128E",
        provider="Meta",
        family="Llama",
        params="400B",
        params_billions=400,
        architecture="moe",
        context_length=1048576,
        use_case=['chat', 'vision', 'reasoning', 'code'],
        description="Multimodal MoE with 128 experts — 17B active, 1M context",
        min_ram_gb=223.5,
        recommended_ram_gb=372.5,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=128.6, disk_gb=122.2, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=179.8, disk_gb=171.1, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=205.4, disk_gb=195.6, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=256.6, disk_gb=244.5, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=307.8, disk_gb=293.4, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=410.3, disk_gb=391.2, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=820.1, disk_gb=782.3, quality="lossless"),
        ],
        active_params="17B active",
        moe_info={'numExperts': 128, 'activeExperts': 1, 'activeParameters': 17000000000},
        ollama_id="llama4:maverick",
        license="Llama 4 Community",
    ),
    AIModel(
        id="qwen3-235b-a22b",
        name="Qwen 3 235B-A22B",
        provider="Alibaba",
        family="Qwen",
        params="235B",
        params_billions=235,
        architecture="moe",
        context_length=131072,
        use_case=['chat', 'code', 'reasoning'],
        description="Massive MoE with 22B active — frontier quality",
        min_ram_gb=131.3,
        recommended_ram_gb=218.9,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=75.7, disk_gb=71.8, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=105.8, disk_gb=100.5, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=120.9, disk_gb=114.9, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=151.0, disk_gb=143.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=181.1, disk_gb=172.4, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=241.2, disk_gb=229.8, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=482.0, disk_gb=459.6, quality="lossless"),
        ],
        active_params="22B active",
        moe_info={'numExperts': 128, 'activeExperts': 8, 'activeParameters': 22000000000},
        ollama_id="qwen3:235b-a22b",
        license="Apache 2.0",
    ),
    AIModel(
        id="qwen3.5-397b-a17b",
        name="Qwen 3.5 397B-A17B",
        provider="Alibaba",
        family="Qwen",
        params="397B",
        params_billions=397,
        architecture="moe",
        context_length=262144,
        use_case=['chat', 'vision', 'reasoning', 'code'],
        description="Largest multimodal Qwen 3.5 MoE",
        min_ram_gb=221.8,
        recommended_ram_gb=369.7,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=127.6, disk_gb=121.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=178.4, disk_gb=169.8, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=203.9, disk_gb=194.1, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=254.7, disk_gb=242.6, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=305.5, disk_gb=291.2, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=407.2, disk_gb=388.2, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=813.9, disk_gb=776.4, quality="lossless"),
        ],
        active_params="17B active",
        moe_info={'numExperts': 256, 'activeExperts': 8, 'activeParameters': 17000000000},
        ollama_id="qwen3.5:397b-cloud",
        license="Apache 2.0",
    ),
    AIModel(
        id="llama3.1-405b",
        name="Llama 3.1 405B",
        provider="Meta",
        family="Llama",
        params="405B",
        params_billions=405,
        architecture="dense",
        context_length=131072,
        use_case=['chat', 'reasoning', 'code'],
        description="Largest open-weight dense model by Meta",
        min_ram_gb=226.3,
        recommended_ram_gb=377.2,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=130.2, disk_gb=123.8, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=182.0, disk_gb=173.3, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=208.0, disk_gb=198.0, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=259.8, disk_gb=247.5, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=311.7, disk_gb=297.0, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=415.4, disk_gb=396.0, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=830.3, disk_gb=792.1, quality="lossless"),
        ],
        ollama_id="llama3.1:405b",
        license="Llama 3.1 Community",
    ),
    AIModel(
        id="qwen3-coder-480b",
        name="Qwen 3 Coder 480B",
        provider="Alibaba",
        family="Qwen",
        params="480B",
        params_billions=480,
        architecture="moe",
        context_length=262144,
        use_case=['code'],
        description="Largest open coding MoE — 35B active",
        min_ram_gb=268.2,
        recommended_ram_gb=447.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=154.2, disk_gb=146.7, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=215.6, disk_gb=205.4, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=246.4, disk_gb=234.7, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=307.8, disk_gb=293.4, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=369.3, disk_gb=352.0, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=492.2, disk_gb=469.4, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=984.0, disk_gb=938.8, quality="lossless"),
        ],
        active_params="35B active",
        moe_info={'numExperts': 128, 'activeExperts': 8, 'activeParameters': 35000000000},
        ollama_id="qwen3-coder:480b",
        license="Apache 2.0",
    ),
    AIModel(
        id="deepseek-r1",
        name="DeepSeek R1",
        provider="DeepSeek",
        family="DeepSeek",
        params="671B",
        params_billions=671,
        architecture="moe",
        context_length=65536,
        use_case=['reasoning'],
        description="Massive MoE reasoning model — 37B active",
        min_ram_gb=375.0,
        recommended_ram_gb=624.9,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=215.3, disk_gb=205.1, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=301.2, disk_gb=287.1, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=344.2, disk_gb=328.1, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=430.1, disk_gb=410.1, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=516.1, disk_gb=492.1, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=687.9, disk_gb=656.2, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=1375.3, disk_gb=1312.3, quality="lossless"),
        ],
        active_params="37B active",
        moe_info={'numExperts': 256, 'activeExperts': 8, 'activeParameters': 37000000000},
        ollama_id="deepseek-r1:671b",
        featured=True,
        license="MIT",
    ),
    AIModel(
        id="deepseek-v3.1",
        name="DeepSeek V3.1",
        provider="DeepSeek",
        family="DeepSeek",
        params="671B",
        params_billions=671,
        architecture="moe",
        context_length=131072,
        use_case=['chat', 'code', 'reasoning'],
        description="Improved V3 with hybrid thinking and tool use",
        min_ram_gb=375.0,
        recommended_ram_gb=624.9,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=215.3, disk_gb=205.1, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=301.2, disk_gb=287.1, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=344.2, disk_gb=328.1, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=430.1, disk_gb=410.1, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=516.1, disk_gb=492.1, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=687.9, disk_gb=656.2, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=1375.3, disk_gb=1312.3, quality="lossless"),
        ],
        active_params="37B active",
        moe_info={'numExperts': 256, 'activeExperts': 8, 'activeParameters': 37000000000},
        ollama_id="deepseek-v3.1",
        license="MIT",
    ),
    AIModel(
        id="deepseek-v3.2",
        name="DeepSeek V3.2",
        provider="DeepSeek",
        family="DeepSeek",
        params="685B",
        params_billions=685,
        architecture="moe",
        context_length=131072,
        use_case=['chat', 'code', 'reasoning'],
        description="State-of-the-art MoE — 37B active params",
        min_ram_gb=382.8,
        recommended_ram_gb=638.0,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=219.8, disk_gb=209.3, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=307.5, disk_gb=293.1, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=351.4, disk_gb=334.9, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=439.1, disk_gb=418.7, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=526.8, disk_gb=502.4, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=702.3, disk_gb=669.9, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=1404.0, disk_gb=1339.7, quality="lossless"),
        ],
        active_params="37B active",
        moe_info={'numExperts': 256, 'activeExperts': 8, 'activeParameters': 37000000000},
        ollama_id="deepseek-v3.2",
        featured=True,
        license="MIT",
    ),
    AIModel(
        id="kimi-k2",
        name="Kimi K2",
        provider="Moonshot AI",
        family="Kimi",
        params="1T",
        params_billions=1000,
        architecture="moe",
        context_length=131072,
        use_case=['chat', 'reasoning', 'code'],
        description="1T-param MoE with 384 experts — 32B active, strong agentic coding",
        min_ram_gb=558.8,
        recommended_ram_gb=931.3,
        quants=[
            Quantization(name="Q2_K", bits=2, vram_gb=320.6, disk_gb=305.6, quality="low"),
            Quantization(name="Q3_K_M", bits=3, vram_gb=448.7, disk_gb=427.8, quality="moderate"),
            Quantization(name="Q4_K_M", bits=4, vram_gb=512.7, disk_gb=488.9, quality="good"),
            Quantization(name="Q5_K_M", bits=5, vram_gb=640.8, disk_gb=611.2, quality="good"),
            Quantization(name="Q6_K", bits=6, vram_gb=768.8, disk_gb=733.4, quality="excellent"),
            Quantization(name="Q8_0", bits=8, vram_gb=1025.0, disk_gb=977.9, quality="excellent"),
            Quantization(name="F16", bits=16, vram_gb=2049.4, disk_gb=1955.8, quality="lossless"),
        ],
        active_params="32B active",
        moe_info={'numExperts': 384, 'activeExperts': 8, 'activeParameters': 32000000000},
        ollama_id="kimi-k2",
        featured=True,
        license="Kimi",
    ),
]
